/**
 * Concrete stock-photo scenes for function words and other vocabulary that
 * cannot be searched literally on Pexels/Unsplash.
 */

import { singularizeForLookup } from "@/lib/word-singularize";

const WORD_SCENES: Readonly<Record<string, string>> = {
  unless: "rain storm window person staying indoors",
  although: "person climbing mountain despite challenge",
  though: "person climbing mountain despite challenge",
  however: "surprised person unexpected change reaction",
  therefore: "logic flowchart arrows whiteboard planning",
  otherwise: "warning sign caution alternative route",
  whether: "person choosing between two options hands",
  because: "cause and effect domino chain reaction",
  since: "calendar timeline past to present",
  until: "hourglass sand time waiting patience",
  while: "person waiting coffee shop reading",
  somewhere: "open country road leading distant hills",
  anywhere: "world map travel pins destinations",
  everywhere: "busy city street crowd people walking",
  nowhere: "empty desert road no people horizon",
  somehow: "person solving puzzle lightbulb idea",
  somewhat: "thermometer partial level measurement",
  rather: "person choosing between two coffee cups",
  maybe: "person shrugging shoulders uncertain choice",
  perhaps: "person thinking uncertain chin hand",
  probably: "weather forecast cloudy sky prediction",
  certainly: "green check mark confirmed approval",
  definitely: "thumbs up confident agreement gesture",
  really: "surprised face genuine reaction closeup",
  quite: "measuring cup partial fill kitchen",
  almost: "finish line runner nearly complete race",
  already: "checked todo list completed tasks desk",
  still: "person sitting still meditation calm lake",
  yet: "empty plate waiting food restaurant table",
  ever: "long winding road lifetime journey horizon",
  never: "prohibited no entry red sign stop",
  always: "sunrise every morning sky horizon",
  often: "repeated calendar appointments weekly routine",
  sometimes: "partly cloudy sky changing weather",
  usually: "morning coffee routine kitchen habit",
  soon: "clock showing time almost hour deadline",
  later: "calendar reminder postponed future date",
  early: "sunrise dawn early morning sky",
  late: "dark night city lights running hurry",
  quickly: "runner sprinting fast motion blur",
  slowly: "snail slow garden closeup macro",
  carefully: "hands carefully carrying fragile glass",
  suddenly: "lightning storm flash dramatic sky",
  finally: "finish line celebration arms raised",
  especially: "highlighted star favorite marked item",
  exactly: "ruler precise measurement exact length",
  nearly: "jigsaw puzzle almost complete last piece",
  hardly: "empty wallet nearly no money left",
  mostly: "pie chart mostly filled percentage graph",
  together: "friends group hugging smiling outdoors",
  apart: "two chairs separated empty room distance",
  instead: "swap exchange two different products hands",
  besides: "additional extra item beside main object",
  plus: "plus sign addition math notebook",
  minus: "minus sign subtraction chalkboard math",
};

const NOUN_HINTS: Readonly<Record<string, string>> = {
  accident: "car accident traffic road emergency",
  account: "online banking account laptop screen",
  address: "envelope home address mail delivery",
  advice: "friendly advice conversation two people",
  afternoon: " sunny afternoon park bench shade",
  age: "birthday cake candles aging celebration",
  agent: "real estate agent showing house keys",
  animal: "cute animal wildlife nature closeup",
  apartment: "modern apartment living room interior",
  army: "soldiers marching uniform formation",
  art: "art gallery painting museum wall",
  attack: "self defense martial arts training",
  attention: "raised hand classroom student question",
  aunt: "family aunt niece hug smiling",
  bag: "leather handbag shopping city street",
  ball: "soccer ball grass field sport",
  band: "live music band concert stage lights",
  bank: "bank building finance city exterior",
  bar: "coffee bar counter espresso machine",
  bathroom: "clean modern bathroom sink mirror",
  beach: "sandy beach ocean waves sunny day",
  bear: "brown bear forest wildlife nature",
  beauty: "flower beauty nature soft petals macro",
  beer: "glass beer pub restaurant table",
  blood: "blood donation medical healthcare hospital",
  boat: "small boat lake calm water rowing",
  body: "fitness body workout gym health",
  book: "open book reading cozy library",
  box: "cardboard box package delivery doorstep",
  boy: "happy boy playing outside playground",
  bread: "fresh bread bakery loaf wooden table",
  brother: "brothers playing together backyard smile",
  building: "office building city skyline architecture",
  bus: "city bus public transport street",
  business: "business meeting handshake office suit",
  camera: "camera photography dslr hands",
  car: "red car road driving transportation",
  card: "credit card payment shopping checkout",
  care: "nurse patient care hospital compassion",
  cat: "cat sitting window sunlight pet",
  chair: "wooden chair empty room minimal",
  chance: "dice rolling game luck table",
  change: "coins change purse money cash",
  child: "happy child playing toys floor",
  city: "city skyline aerial view buildings",
  class: "classroom students desks teacher board",
  clock: "wall clock time office interior",
  clothes: "clothes wardrobe fashion hanger rack",
  coffee: "hot coffee cup morning table",
  cold: "winter cold snow scarf outdoors",
  color: "colorful paint palette art studio",
  company: "team meeting office collaboration laptop",
  computer: "laptop computer desk workspace modern",
  conversation: "two people conversation cafe table",
  cost: "price tag shopping cost money receipt",
  country: "countryside green fields landscape flag",
  course: "golf course green lawn sport",
  court: "basketball court game sport indoor",
  cover: "book cover design magazine stack",
  cry: "person crying tears emotional closeup",
  culture: "world culture diversity people festival",
  cup: "ceramic coffee cup steam morning",
  dance: "couple dance ballroom elegant motion",
  danger: "warning sign danger cliff edge",
  date: "calendar date circled red marker planner",
  day: "bright sunny day blue sky clouds",
  death: "memorial candle remembrance quiet scene",
  decision: "crossroads fork path choice decision",
  dog: "golden retriever dog park happy",
  door: "open door light hallway welcome",
  dream: "person dreaming sleep peaceful bedroom",
  dress: "elegant dress fashion model studio",
  disgrace: "person ashamed embarrassed covering face hands",
  drink: "refreshing drink glass ice lemon",
  driver: "car driver steering wheel road trip",
  earth: "planet earth globe environment nature",
  east: "sunrise east horizon golden sky",
  edge: "cliff edge mountain view dramatic",
  egg: "fresh eggs basket farm breakfast",
  energy: "lightning energy power electric bolt",
  evening: "evening sunset city lights golden hour",
  eye: "human eye closeup iris detail",
  face: "smiling face portrait happy person",
  fact: "magnifying glass document research facts",
  fall: "autumn fall leaves forest orange",
  family: "happy family picnic park together",
  farm: "farm field tractor rural countryside",
  father: "father son bonding park walking",
  fear: "person afraid dark shadow nervous",
  field: "green field wheat agriculture horizon",
  fight: "boxing training sport gym fighters",
  figure: "human figure silhouette sunset beach",
  film: "movie film clapperboard cinema production",
  fire: "campfire flames night outdoor warmth",
  fish: "fish swimming aquarium underwater blue",
  floor: "wooden floor interior home clean",
  flower: "colorful flower garden bloom spring",
  food: "healthy food plate vegetables table",
  foot: "barefoot sand beach walking feet",
  force: "strong wind tree bending force nature",
  form: "application form pen signing document",
  friend: "friends laughing cafe friendship together",
  front: "house front door entrance welcome mat",
  game: "board game friends playing table fun",
  garden: "beautiful garden flowers path spring",
  gas: "gas station fuel pump car refuel",
  girl: "girl reading book library smile",
  glass: "water glass clear table refreshment",
  god: "church stained glass light peaceful",
  gold: "gold bars wealth finance shiny",
  ground: "ground soil earth gardening hands",
  group: "diverse group people team together smiling",
  growth: "plant seedling growth soil green sprout",
  hair: "hair salon styling mirror haircut",
  hand: "helping hand support friendship reach",
  head: "head shoulders portrait professional studio",
  health: "healthy lifestyle salad fitness yoga",
  heart: "heart shape hands gesture love",
  heat: "summer heat sun hot desert mirage",
  history: "old history books antique library archive",
  hit: "baseball bat hitting ball sport action",
  hole: "hole in ground earth digging garden",
  hope: "person looking sunrise horizon hopeful",
  horse: "horse riding meadow countryside gallop",
  hospital: "hospital building healthcare medical entrance",
  hotel: "hotel lobby reception travel luggage",
  hour: "clock hour time waiting office wall",
  house: "cozy house exterior suburban home",
  human: "diverse people faces portrait together",
  husband: "married couple wedding rings hands love",
  idea: "lightbulb idea innovation creative thinking",
  image: "camera taking photo landscape photographer",
  industry: "factory industry production manufacturing plant",
  interest: "person reading interesting book focused",
  island: "tropical island beach palm ocean aerial",
  issue: "newspaper headline news current issue",
  job: "job interview office handshake professional",
  joy: "person jumping joy celebration happy outdoors",
  judge: "judge gavel courtroom law justice",
  jump: "person jumping trampoline fun action air",
  kid: "kids playing playground happy children",
  kill: "hunter aim target sport archery range",
  king: "chess king piece strategy board game",
  kitchen: "modern kitchen cooking food preparation",
  land: "airplane landing runway airport travel",
  language: "language learning books globe education",
  law: "law scales justice courthouse columns",
  leg: "running legs marathon sport motion",
  letter: "handwritten letter envelope stamp mail",
  level: "spirit level tool construction straight line",
  life: "newborn baby hands family life beginning",
  light: "sunlight window room bright morning rays",
  line: "people standing queue line waiting",
  list: "checklist todo list planner notebook pen",
  love: "couple holding hands sunset romance",
  lunch: "healthy lunch box office desk meal",
  machine: "industrial machine factory production gear",
  man: "man walking city street business casual",
  map: "travel map planning route adventure",
  mark: "red mark highlighter document important text",
  market: "farmers market fresh produce vegetables stall",
  marriage: "wedding couple rings ceremony flowers",
  matter: "science matter molecules laboratory glassware",
  meal: "family dinner table food sharing meal",
  meat: "grilled meat steak barbecue restaurant plate",
  media: "social media phone scrolling news apps",
  mind: "meditation mind calm brain wellness peace",
  minute: "minute hand clock closeup time passing",
  missile: "rocket missile launch smoke sky military",
  moment: "camera capturing special moment candid photo",
  money: "cash money dollars savings wallet",
  month: "calendar month planner schedule organizer",
  moon: "full moon night sky stars dark",
  morning: "morning coffee sunrise kitchen window light",
  mother: "mother child hug love family home",
  mouth: "smile mouth teeth happy laughing closeup",
  move: "moving boxes new home relocation cardboard",
  movie: "cinema movie theater popcorn screen dark",
  music: "headphones music listening enjoyment relaxing",
  name: "name tag badge conference introduction",
  nation: "national flag waving wind patriotism sky",
  nature: "nature forest trail hiking green trees",
  news: "newspaper reading morning coffee table",
  night: "city night lights skyline dark blue",
  noise: "construction noise city street traffic loud",
  north: "compass north direction navigation map travel",
  nose: "dog nose closeup smell sniff macro",
  note: "sticky notes reminder board planning office",
  number: "numbers chalkboard math classroom education",
  office: "modern office workspace desk computer",
  oil: "olive oil bottle kitchen cooking ingredient",
  page: "book page turning reading literature open",
  pain: "person holding knee pain injury support",
  paint: "artist paint brush canvas colorful art",
  pair: "pair of shoes matching sneakers display",
  paper: "white paper blank sheet desk pen",
  parent: "parents children park family walking together",
  park: "city park bench trees green relaxing",
  part: "puzzle part piece connecting teamwork closeup",
  party: "birthday party balloons cake celebration friends",
  pass: "mountain pass road winding scenic drive",
  past: "old photo album memories vintage nostalgic",
  peace: "dove peace symbol white bird sky",
  person: "person portrait candid smile natural light",
  phone: "smartphone hand texting modern mobile screen",
  photo: "photographer taking photo camera outdoor shoot",
  picture: "picture frame wall home decor interior",
  piece: "jigsaw puzzle piece fitting together hands",
  place: "favorite place cozy cafe window rain",
  plan: "architect planning blueprint desk ruler pencil",
  plant: "indoor plant pot green home decor",
  play: "children playing playground slide happy park",
  point: "finger pointing direction guide showing way",
  police: "police officer uniform patrol street safety",
  policy: "policy document signing agreement office desk",
  position: "yoga position balance exercise mat studio",
  power: "electric power lines sunset energy grid",
  press: "newspaper press printing media journalism office",
  price: "price tag retail shopping store sale",
  problem: "person solving problem whiteboard brainstorming team",
  process: "factory process conveyor belt production line",
  product: "retail product shelf store shopping display",
  program: "laptop coding program developer screen software",
  property: "house property real estate for sale sign",
  public: "public transport bus city commuters crowd",
  pull: "person pulling suitcase airport travel walk",
  purpose: "target goal dartboard aim purpose focus",
  push: "person pushing shopping cart supermarket aisle",
  quality: "quality check magnifying glass product inspection",
  question: "question mark chalkboard curiosity thinking student",
  radio: "vintage radio music retro device wooden",
  rain: "rain drops window glass storm weather city",
  range: "mountain range panoramic view landscape snow peaks",
  rash: "skin rash red irritation arm closeup medical",
  rate: "interest rate graph chart finance screen",
  reason: "lightbulb reason logic thinking desk notes",
  record: "vinyl record turntable music retro listening",
  red: "red color sample fabric texture closeup",
  region: "map region highlighted area geography travel",
  relation: "family relation generations tree portrait wall",
  research: "scientist research microscope laboratory study",
  rest: "person resting hammock shade peaceful relax",
  result: "exam result score paper graded checkmark",
  return: "product return store counter customer service",
  right: "right turn road sign direction arrow",
  ring: "diamond ring jewelry box engagement proposal",
  river: "river flowing forest landscape peaceful water",
  road: "empty road countryside travel adventure horizon",
  rock: "rock climbing outdoor sport adventure cliff",
  role: "theater role mask drama performance stage",
  room: "cozy room interior lamp warm light reading",
  rule: "rule book law handbook desk official document",
  run: "person running park trail morning exercise",
  safe: "safe lock vault security metal bank",
  sale: "sale sign shop discount retail storefront",
  salt: "salt shaker kitchen cooking seasoning table",
  sand: "wet sand beach footprint waves shore",
  save: "piggy bank saving money coins finance",
  scene: "movie scene filming camera set production",
  school: "school building students entrance education campus",
  sea: "calm sea horizon blue water boat sailing",
  seat: "empty seat train window travel waiting",
  second: "stopwatch second timer sport race track",
  section: "library book section aisle shelves reading",
  sense: "five senses icons taste smell touch chart",
  series: "tv series remote couch streaming entertainment",
  service: "customer service headset support agent smile",
  set: "dinner table place setting elegant restaurant",
  sex: "gender symbols equality diversity people together",
  shape: "geometric shapes colorful blocks learning kids",
  share: "sharing food friends picnic divide plate",
  ship: "cargo ship ocean freight transport sailing",
  shirt: "folded shirt clothing store fashion retail",
  shock: "surprised shocked face expression wide eyes",
  shoe: "running shoes pair fitness sport gym floor",
  shop: "small shop storefront street local business",
  shot: "basketball shot hoop sport action gym",
  show: "theater show stage curtains spotlight performance",
  side: "side by side comparison two products table",
  sign: "road sign traffic direction street urban",
  site: "construction site building crane workers helmet",
  size: "measuring size tape tailor clothing fit",
  skin: "skincare skin care cream spa treatment",
  sky: "blue sky white clouds sunny day wide",
  sleep: "person sleeping peacefully bed soft pillow",
  smile: "genuine smile portrait happy person closeup",
  smoke: "smoke steam coffee cup morning warm",
  snow: "snow falling winter street cozy lights",
  society: "diverse society community people city street",
  son: "father son playing catch park bonding",
  song: "singer microphone music studio recording song",
  sort: "sorting laundry colors baskets organization home",
  sound: "sound waves music speaker audio studio",
  source: "water source spring mountain stream nature fresh",
  south: "compass south navigation map travel direction",
  space: "outer space stars galaxy universe dark",
  speak: "public speaking microphone presentation audience hall",
  speed: "speedometer car dashboard fast driving motion",
  sport: "sport stadium field athletes competition game",
  spring: "spring flowers blossom park season colorful",
  staff: "office staff team meeting collaboration laptops",
  stage: "empty stage spotlight theater performance curtains",
  stand: "person standing queue line waiting patiently",
  star: "night sky stars milky way astronomy dark",
  start: "starting line race runners ready sprint",
  state: "state map usa geography highlighted region",
  station: "train station platform commute travel urban",
  stay: "hotel stay cozy bed room travel luggage",
  step: "footsteps stairs climbing upward progress path",
  stick: "walking stick hike mountain trail outdoor",
  stock: "stock market chart screen finance trading desk",
  stone: "stone path garden zen peaceful arrangement",
  stop: "red stop sign street intersection traffic",
  store: "grocery store aisle shopping cart products",
  story: "storytelling book children bedtime reading lamp",
  street: "busy street crosswalk city people walking",
  stress: "stressed person desk head hands overwhelmed work",
  strike: "bowling strike pins sport indoor alley",
  strong: "strong person lifting weights gym fitness",
  student: "student studying library books laptop focus",
  study: "student study desk lamp books notes night",
  style: "fashion style outfit mirror boutique clothing",
  subject: "school subject books math science stack desk",
  success: "success celebration trophy winner achievement happy",
  sugar: "sugar cubes coffee tea spoon sweet",
  summer: "summer beach sunshine vacation tropical palm",
  sun: "bright sun sky sunshine warm golden light",
  supply: "office supplies pens notebooks organized desk drawer",
  support: "support hands together teamwork help uplift",
  surface: "calm water surface ripple reflection lake",
  surprise: "surprise gift box celebration party excited",
  system: "computer system network servers technology data center",
  table: "wooden dining table set family home interior",
  talk: "two friends talking cafe conversation laughing",
  tax: "tax form calculator finance desk paperwork april",
  tea: "hot tea cup steam cozy morning window",
  team: "team huddle sports cooperation motivation circle",
  technology: "technology gadgets laptop phone innovation desk modern",
  television: "television living room family watching cozy sofa",
  tell: "storytelling grandfather child listening warm fireplace",
  term: "dictionary term definition book page reading study",
  test: "student test exam paper pencil classroom desk",
  text: "text message smartphone chatting communication screen closeup",
  thank: "thank you note gratitude card handwritten envelope",
  thing: "miscellaneous things organized shelf storage boxes labeled",
  thought: "person thinking deep thought window rainy day",
  throw: "person throwing frisbee park outdoor fun action",
  time: "wall clock time passing office meeting schedule",
  title: "book title cover spine library shelf row",
  today: "today calendar date marked planner desk morning",
  toe: "barefoot toes sand beach walk closeup",
  top: "mountain top summit view achievement flag peak",
  touch: "hands touch screen tablet technology interaction",
  town: "small town main street shops charming usa",
  track: "running track athlete training sport stadium lanes",
  trade: "international trade shipping containers port cargo",
  train: "passenger train station platform commute travel",
  travel: "travel suitcase airport departure adventure world",
  tree: "large tree green park shade nature sunlight",
  trial: "court trial judge gavel law justice scales",
  trip: "road trip car highway adventure friends fun",
  trouble: "car trouble broken down roadside help phone",
  true: "true false checkbox form survey decision choice",
  trust: "handshake trust partnership agreement business deal",
  truth: "truth honesty mirror reflection authentic self portrait",
  turn: "road turn arrow sign direction winding curve",
  type: "keyboard typing laptop work office hands closeup",
  unit: "apartment unit building residential urban modern balcony",
  use: "person using smartphone app daily life urban",
  value: "value price tag quality product retail shopping",
  view: "scenic view mountain landscape panorama breathtaking nature",
  visit: "visit friends welcome door greeting smile home",
  voice: "singer recording voice microphone studio music",
  walk: "person walking dog park path autumn leaves",
  wall: "brick wall texture pattern urban background detail",
  war: "anti war peace dove symbol white bird",
  warm: "warm blanket cozy fireplace winter home comfort",
  watch: "wristwatch time closeup elegant hand classic",
  water: "clear water glass refreshment table light",
  way: "crossroads path choice way direction sign forest",
  week: "weekly planner calendar schedule organized desk office",
  weight: "gym weights fitness training strength dumbbells floor",
  west: "western sunset desert cactus golden hour landscape",
  wife: "couple wedding rings married hands love commitment",
  win: "winner trophy celebration victory sport team happy",
  wind: "wind turbine renewable energy field sky clouds",
  window: "window rain drops cozy interior view outside",
  wine: "wine glass vineyard toast celebration elegant dinner",
  winter: "winter snow street lights cozy cold season",
  wish: "dandelion wish blowing seeds sunset dreamy field",
  woman: "professional woman portrait confident smile office",
  wonder: "person wondering looking stars night sky awe",
  wood: "wood texture grain natural material carpentry table",
  word: "dictionary open vocabulary learning desk study lamp",
  work: "office work laptop desk focused professional modern",
  worker: "construction worker helmet safety building site hardhat",
  world: "world globe earth map travel exploration education",
  worry: "worried person thinking problem chin hand desk",
  worth: "worth value coins savings jar financial planning",
  write: "person writing journal notebook pen cozy desk",
  writer: "writer typing laptop coffee shop creative workspace",
  wrong: "wrong answer red x mark paper mistake",
  yard: "backyard garden lawn house suburban green grass",
  year: "calendar new year celebration fireworks night sky",
  yes: "yes nod agreement thumbs up positive gesture smile",
  yesterday: "calendar yesterday date crossed planner reflection journal",
  young: "young couple smiling outdoors adventure travel happy",
  youth: "youth group friends laughing park summer fun",
};

function cleanWord(word: string): string {
  return word.trim().toLowerCase();
}

function lookupSceneKey(key: string): string | null {
  if (WORD_SCENES[key]) return WORD_SCENES[key];
  if (NOUN_HINTS[key]) return NOUN_HINTS[key];
  return null;
}

export function lookupAbstractImageScene(
  word: string,
  pos?: string | null,
): string | null {
  const key = cleanWord(word);
  if (!key) return null;

  const direct = lookupSceneKey(key) ?? lookupSceneKey(singularizeForLookup(key));
  if (direct) return direct;

  if (key.endsWith("where")) {
    if (key.includes("any")) return "world map travel destinations pins";
    if (key.includes("every")) return "crowded street people walking busy city";
    if (key.includes("no")) return "empty road desert horizon lonely landscape";
    return "open road distant hills unknown destination";
  }

  if (key.endsWith("when")) return "analog clock showing specific time closeup";
  if (key.endsWith("wise")) return "wise mentor giving advice conversation office";
  if (key.endsWith("ful")) return "happy satisfied person smiling achievement moment";

  const normalizedPos = pos?.trim().toLowerCase();
  if (normalizedPos === "conjunction") {
    return "fork road two paths decision choice sign";
  }
  if (normalizedPos === "adverb") {
    return "candid daily life street photography person walking";
  }
  if (normalizedPos === "preposition") {
    return "people spatial arrangement room furniture layout";
  }
  if (normalizedPos === "pronoun" || normalizedPos === "determiner") {
    return "diverse group people together smiling portrait";
  }
  if (normalizedPos === "adjective") {
    return "descriptive scene person environment portrait natural light";
  }
  if (normalizedPos === "verb") {
    return "person action everyday activity candid photo";
  }

  return null;
}
