/**
 * Auto-curate concrete stock-photo search phrases for any vocabulary word.
 * Used at runtime (with meaning) and by scripts/generate-curated-keywords.ts.
 */

import { lookupAbstractImageScene } from "@/lib/abstract-image-scenes";
import { getStaticWordDetail } from "@/data/preset-word-details";
import { getStandardVocab } from "@/data/standard-vocab";
import { resolveHomonymImageKeyword } from "@/lib/homonym-image-keywords";
import { resolveMeaningImageKeyword } from "@/lib/meaning-image-keywords";
import { isWeakAutoGeneratedPhrase } from "@/lib/image-keyword-utils";
import { diversifiedStockScene } from "@/lib/stock-scene-fallbacks";
import { singularizeForLookup } from "@/lib/word-singularize";
import { normalizeWordType } from "@/lib/word-type";
import { CURATED_IMAGE_KEYWORDS_RANK_1_100 } from "@/data/curated-image-keywords-rank-1-100";
import { CURATED_IMAGE_OVERRIDES } from "@/data/curated-image-overrides";

const COLORS = new Set([
  "orange", "brown", "pink", "purple", "gray", "grey", "green", "red",
  "blue", "yellow", "black", "white", "golden", "silver",
]);

const WEEKDAYS = new Set([
  "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
]);

const MONTHS = new Set([
  "january", "february", "march", "april", "may", "june", "july", "august",
  "september", "october", "november", "december",
]);

const DEFINITION_STOPWORDS = new Set([
  "a", "an", "the", "and", "or", "of", "to", "in", "on", "at", "by", "for",
  "with", "from", "that", "this", "these", "those", "is", "are", "was", "were",
  "be", "been", "being", "have", "has", "had", "do", "does", "did", "will",
  "would", "could", "should", "may", "might", "can", "who", "which", "what",
  "when", "where", "how", "why", "very", "also", "just", "only", "not", "no",
  "such", "than", "then", "into", "through", "during", "before", "after",
  "above", "below", "between", "under", "over", "again", "further", "once",
  "here", "there", "all", "each", "few", "more", "most", "other", "some",
  "any", "both", "own", "same", "so", "too", "about", "against", "used",
  "using", "use", "make", "made", "making", "one", "two", "three", "something",
  "someone", "somebody", "anything", "nothing", "everything", "person", "people",
  "thing", "things", "word", "words", "like", "well", "way",
]);

export type CurateImageKeywordOptions = {
  meaning?: string | null;
  englishDefinition?: string | null;
  pos?: string | null;
  searchKeyword?: string | null;
};

function cleanWord(word: string): string {
  return word.trim().toLowerCase().replace(/[^a-z0-9'-]/g, "") || "";
}

function inferPos(word: string): string {
  const staticDetail = getStaticWordDetail(word);
  if (staticDetail?.pos) return staticDetail.pos.toLowerCase();
  const std = getStandardVocab(word);
  if (std?.pos) return std.pos.toLowerCase();
  return normalizeWordType(null, word) ?? "noun";
}

function definitionToImageQuery(definition: string, word: string): string | null {
  const tokens = definition
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .split(/\s+/)
    .filter(
      (token) =>
        token.length > 2 &&
        !DEFINITION_STOPWORDS.has(token) &&
        token !== word &&
        token !== singularizeForLookup(word),
    );
  if (tokens.length < 2) return null;
  return `${tokens.slice(0, 5).join(" ")} photo`;
}

function isConcreteStoredKeyword(keyword: string, word: string): boolean {
  const trimmed = keyword.trim().toLowerCase();
  if (!trimmed || trimmed === word) return false;
  if (isWeakAutoGeneratedPhrase(trimmed, word)) return false;
  return trimmed.includes(" ") || trimmed.length > word.length + 2;
}

function obscureNounFallback(key: string, singular: string): string {
  if (/(ist|ian)$/.test(key)) return `professional ${singular} worker portrait`;
  if (/(eer|ier)$/.test(key)) return `skilled ${singular} person activity photo`;
  if (/(er|or)$/.test(key) && key.length > 4) {
    return `${singular} person working activity photo`;
  }
  if (/ism$/.test(key)) return `${key.slice(0, -3)} concept symbolic illustration`;
  if (/ology$/.test(key)) return `scientific research laboratory study photo`;
  if (/ship$/.test(key)) return `${key.slice(0, -4)} relationship people together`;
  if (/hood$/.test(key)) return `${key.slice(0, -4)} community neighborhood scene`;
  if (/ware$/.test(key)) return `software technology computer screen office`;
  if (key.includes("-")) {
    const parts = key.split("-").filter((part) => part.length > 2);
    if (parts.length >= 2) return `${parts.join(" ")} scene photo`;
  }
  if (/(line|headline|heading|title|news|paper)$/.test(key)) {
    return `${singular} newspaper headline media closeup`;
  }
  return diversifiedStockScene(key);
}

function obscureWordFallback(
  key: string,
  singular: string,
  pos: string,
): string {
  if (pos === "verb") {
    const stem = key.endsWith("ing") ? singular : key;
    return `person ${stem} everyday activity candid photo`;
  }
  if (pos === "adjective") return diversifiedStockScene(key);
  if (pos === "adverb") return "candid daily life street photography person walking";
  if (pos === "preposition" || pos === "conjunction") {
    return "fork road two paths decision choice sign";
  }
  if (pos === "pronoun" || pos === "determiner" || pos === "article") {
    return "diverse group people together smiling portrait";
  }
  if (
    key.endsWith("tion") ||
    key.endsWith("ness") ||
    key.endsWith("ment") ||
    key.endsWith("ity")
  ) {
    const stem = key.replace(/(tion|ness|ment|ity)$/, "");
    return `${stem} concept workplace professional scene`;
  }
  return obscureNounFallback(key, singular);
}

/** Best-effort curated phrase for one vocabulary word. */
export function curateImageSearchPhrase(
  word: string,
  options: CurateImageKeywordOptions = {},
): string {
  const key = cleanWord(word) || "vocabulary";
  const singular = singularizeForLookup(key);
  const staticDetail = getStaticWordDetail(key);
  const std = getStandardVocab(key);
  const meaning =
    options.meaning?.trim() ||
    staticDetail?.vietnamese?.trim() ||
    std?.meaning?.trim() ||
    null;
  const englishDefinition =
    options.englishDefinition?.trim() ||
    staticDetail?.definition?.trim() ||
    std?.definition?.trim() ||
    null;
  const pos = options.pos?.trim().toLowerCase() || inferPos(key);

  const homonym = resolveHomonymImageKeyword(key, { meaning, englishDefinition, pos });
  if (homonym) return homonym;

  const meaningKeyword = resolveMeaningImageKeyword(
    { meaning, englishDefinition, pos },
    key,
  );
  if (meaningKeyword) return meaningKeyword;

  const handTuned = CURATED_IMAGE_KEYWORDS_RANK_1_100[key];
  if (handTuned && isConcreteStoredKeyword(handTuned, key)) return handTuned;

  const override = CURATED_IMAGE_OVERRIDES[key];
  if (override && isConcreteStoredKeyword(override, key)) return override;

  const stored = options.searchKeyword?.trim().toLowerCase();
  if (stored && isConcreteStoredKeyword(stored, key)) return stored;

  const stdKw = std?.searchKeyword?.trim().toLowerCase();
  if (stdKw && isConcreteStoredKeyword(stdKw, key)) return stdKw;

  const abstractScene =
    lookupAbstractImageScene(key, pos) ??
    lookupAbstractImageScene(singular, pos);
  if (abstractScene) return abstractScene;

  const fromDefinition = englishDefinition
    ? definitionToImageQuery(englishDefinition, key)
    : null;
  if (fromDefinition && !isWeakAutoGeneratedPhrase(fromDefinition, key)) {
    return fromDefinition;
  }

  const fromMeaning = meaning ? definitionToImageQuery(meaning, key) : null;
  if (fromMeaning && !isWeakAutoGeneratedPhrase(fromMeaning, key)) {
    return fromMeaning;
  }

  if (COLORS.has(key)) return `bright ${key} color sample swatch`;
  if (WEEKDAYS.has(key)) return `calendar showing ${key} weekday planner`;
  if (MONTHS.has(key)) return `calendar page ${key} season month`;
  if (/^\d+$/.test(key) || key.endsWith("teen")) {
    return `number ${key} written classroom chalkboard`;
  }

  return obscureWordFallback(key, singular, pos);
}

export function isAcceptableCuratedPhrase(phrase: string, word: string): boolean {
  const trimmed = phrase.trim();
  if (!trimmed) return false;
  if (isWeakAutoGeneratedPhrase(trimmed, word)) return false;
  return trimmed.includes(" ") || trimmed.length > word.length + 2;
}
