/**
 * Turn a vocabulary word into a concrete stock-photo search phrase for
 * Pexels / Unsplash fallback when the Gemini pipeline is unavailable.
 */

import { lookupAbstractImageScene } from "@/lib/abstract-image-scenes";
import {
  isHomonymWord,
  resolveHomonymImageKeyword,
} from "@/lib/homonym-image-keywords";
import { resolveMeaningImageKeyword } from "@/lib/meaning-image-keywords";
import {
  cleanPhrase,
  isConcretePhrase,
  isWeakAutoGeneratedPhrase,
} from "@/lib/image-keyword-utils";
import { diversifiedStockScene, isLegacyStockScenePhrase } from "@/lib/stock-scene-fallbacks";
import { singularizeForLookup } from "@/lib/word-singularize";

const ABSTRACT_POS = new Set([
  "verb",
  "adjective",
  "adverb",
  "preposition",
  "conjunction",
  "determiner",
  "pronoun",
]);

export function isAbstractImagePos(pos?: string | null): boolean {
  const normalized = pos?.trim().toLowerCase();
  return Boolean(normalized && ABSTRACT_POS.has(normalized));
}

const COLOR_WORDS = new Set([
  "orange",
  "brown",
  "pink",
  "purple",
  "gray",
  "grey",
  "green",
  "red",
  "blue",
  "yellow",
  "black",
  "white",
  "golden",
  "silver",
]);

function inferPosFromWord(word: string): string | null {
  const normalized = cleanPhrase(word);
  if (!normalized) return null;
  if (normalized.endsWith("ly") && normalized.length > 3) return "adverb";
  if (/(tion|ness|ment|ity|ism|ship|ance|ence)$/.test(normalized)) {
    return "noun";
  }
  if (/(ing|ed|ize|ise)$/.test(normalized) && normalized.length > 4) {
    return "verb";
  }
  return null;
}

export { cleanPhrase, isConcretePhrase, isWeakAutoGeneratedPhrase };

type ImageKeywordOptions = {
  searchKeyword?: string | null;
  meaning?: string | null;
  englishDefinition?: string | null;
  pos?: string | null;
};

/**
 * Best single query for Pexels / Unsplash.
 */
export function resolveImageSearchKeyword(
  word: string,
  options: ImageKeywordOptions = {},
): string {
  const normalizedWord = cleanPhrase(word) || "vocabulary";

  const homonymKeyword = resolveHomonymImageKeyword(normalizedWord, {
    meaning: options.meaning,
    englishDefinition: options.englishDefinition,
    pos: options.pos,
  });
  if (homonymKeyword) return homonymKeyword;

  const meaningKeyword = resolveMeaningImageKeyword({
    meaning: options.meaning,
    englishDefinition: options.englishDefinition,
    pos: options.pos,
  });
  if (meaningKeyword) return meaningKeyword;

  const candidate = cleanPhrase(options.searchKeyword ?? "");
  if (
    candidate &&
    !isLegacyStockScenePhrase(candidate) &&
    isConcretePhrase(candidate, normalizedWord) &&
    !isWeakAutoGeneratedPhrase(candidate, normalizedWord)
  ) {
    return candidate;
  }

  const pos =
    options.pos?.trim().toLowerCase() || inferPosFromWord(normalizedWord);

  const abstractScene =
    lookupAbstractImageScene(normalizedWord, pos) ??
    lookupAbstractImageScene(singularizeForLookup(normalizedWord), pos);
  if (abstractScene) return abstractScene;

  if (COLOR_WORDS.has(normalizedWord)) {
    return `bright ${normalizedWord} color sample swatch`;
  }

  if (pos === "noun") {
    return normalizedWord.includes(" ")
      ? normalizedWord
      : `${normalizedWord} object`;
  }
  if (pos === "verb") {
    return `person ${normalizedWord} action scene`;
  }

  return diversifiedStockScene(normalizedWord);
}

/**
 * A long, specific stock-photo phrase (e.g. "hand pointing at nearby
 * object") rarely appears verbatim in a photo's title/tags, so full-text
 * image search engines (Openverse, Wikimedia Commons) often return zero
 * results for it even though a real photo exists. Shorter 2-word slices of
 * the same phrase — which usually keep the core subject + action — match
 * far more reliably. Returns the slices in an order most likely to preserve
 * the meaning of the original phrase.
 */
function shortenPhraseVariants(phrase: string): string[] {
  const tokens = phrase.split(/\s+/).filter(Boolean);
  if (tokens.length <= 2) return [];

  const variants: string[] = [];
  variants.push(tokens.slice(0, 2).join(" "));
  if (tokens.length >= 3) variants.push(tokens.slice(0, 3).join(" "));
  variants.push(tokens.slice(-2).join(" "));

  return [...new Set(variants)].filter((variant) => variant !== phrase);
}

/**
 * Ordered fallbacks when the first Unsplash query returns nothing useful.
 */
export function buildImageSearchQueries(
  word: string,
  options: ImageKeywordOptions = {},
): string[] {
  const primary = resolveImageSearchKeyword(word, options);
  const normalizedWord = cleanPhrase(word) || "vocabulary";
  const queries = new Set<string>([primary]);

  const pos = options.pos?.trim().toLowerCase();
  if (
    primary !== normalizedWord &&
    !isHomonymWord(normalizedWord) &&
    pos === "noun"
  ) {
    queries.add(normalizedWord);
  }

  if (pos === "noun" && !primary.includes(" ")) {
    queries.add(`${primary} object`);
  }

  for (const variant of shortenPhraseVariants(primary)) {
    queries.add(variant);
  }

  return [...queries];
}
