/** Shared helpers for stock-photo keyword resolution (no heavy imports). */

export function cleanPhrase(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Auto-generated rank-band phrases that perform worse than POS heuristics. */
export function isWeakAutoGeneratedPhrase(
  phrase: string,
  word: string,
): boolean {
  const normalized = cleanPhrase(word);
  const cleaned = cleanPhrase(phrase);
  if (!normalized || !cleaned) return false;
  return (
    cleaned === `${normalized} everyday object scene clear photo` ||
    cleaned === `${normalized} everyday life scene clear photo` ||
    cleaned === `${normalized} person action everyday scene` ||
    cleaned === `${normalized} descriptive scene person` ||
    cleaned === `${normalized} object closeup photo` ||
    cleaned === `person acting ${normalized} in daily life` ||
    cleaned === `${normalized} spatial relationship people scene` ||
    cleaned === `people together ${normalized} gesture scene` ||
    cleaned === `person ${normalized} daily life scene` ||
    cleaned === `person acting ${normalized} in daily life` ||
    cleaned === `${normalized} descriptive scene person` ||
    cleaned.endsWith(" object closeup photo") ||
    cleaned.endsWith(" concept office workplace scene") ||
    / concept office scene$/.test(cleaned)
  );
}

export function isConcretePhrase(phrase: string, word: string): boolean {
  const tokens = phrase.split(/\s+/).filter(Boolean);
  if (tokens.length >= 2) return true;
  return tokens.length === 1 && tokens[0] !== word;
}
