/** Shared helpers for stock-photo keyword resolution (no heavy imports). */

export function cleanPhrase(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Auto-generated rank-band phrases that perform worse than POS heuristics. */
export function isWeakAutoGeneratedPhrase(
  phrase: string,
  word: string,
): boolean {
  const normalized = cleanPhrase(word);
  const cleaned = cleanPhrase(phrase);
  if (!normalized || !cleaned) return false;
  return (
    cleaned === `${normalized} everyday object scene clear photo` ||
    cleaned === `${normalized} everyday life scene clear photo` ||
    cleaned === `${normalized} person action everyday scene` ||
    cleaned === `${normalized} descriptive scene person` ||
    cleaned === `${normalized} object closeup photo` ||
    cleaned === `person acting ${normalized} in daily life` ||
    cleaned === `${normalized} spatial relationship people scene` ||
    cleaned === `people together ${normalized} gesture scene` ||
    cleaned === `person ${normalized} daily life scene` ||
    cleaned === `person acting ${normalized} in daily life` ||
    cleaned === `${normalized} descriptive scene person` ||
    cleaned.endsWith(" object closeup photo") ||
    cleaned.endsWith(" still life object photo") ||
    cleaned.endsWith(" concept illustration educational photo") ||
    cleaned.endsWith(" wildlife nature closeup photo") ||
    cleaned.endsWith(" descriptive scene natural light portrait") ||
    cleaned === "descriptive scene person environment portrait natural light" ||
    cleaned.endsWith(" concept office workplace scene") ||
    cleaned.startsWith("clear photograph of ") ||
    / concept office scene$/.test(cleaned)
  );
}

/** Returns true when text is safe to use as an English stock-photo query. */
export function isUsableEnglishImageQuery(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed || trimmed.length < 4) return false;
  if (/[\u00C0-\u1EF9]/.test(trimmed) || /[àáảãạăắằẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđ]/i.test(trimmed)) {
    return false;
  }
  const cleaned = cleanPhrase(trimmed);
  if (!cleaned || cleaned.length < 4) return false;
  const tokens = cleaned.split(/\s+/).filter(Boolean);
  if (tokens.length === 0) return false;
  const shortTokens = tokens.filter((token) => token.length <= 2).length;
  if (shortTokens / tokens.length > 0.35) return false;
  return tokens.some((token) => token.length >= 4);
}

export function hashWordSeed(word: string): number {
  let hash = 0;
  for (const char of word.trim().toLowerCase()) {
    hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  }
  return hash;
}

export function isConcretePhrase(phrase: string, word: string): boolean {
  const tokens = phrase.split(/\s+/).filter(Boolean);
  if (tokens.length >= 2) return true;
  return tokens.length === 1 && tokens[0] !== word;
}
