export type UnsplashPhoto = {
  id: string;
  url: string;
  alt: string;
  photographer: string;
};

type UnsplashSearchResponse = {
  results: Array<{
    id: string;
    alt_description: string | null;
    urls: { regular: string };
    user: { name: string };
  }>;
};

function hashWord(word: string): number {
  let hash = 0;
  for (const char of word.trim().toLowerCase()) {
    hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  }
  return hash;
}

/**
 * Keyword-relevant, unique-per-word photo. LoremFlickr sources a real photo
 * tagged with `word` from Flickr; `lock` pins it to one deterministic image
 * per word so the same card never shuffles between reloads.
 */
export function getLoremFlickrImageUrl(word: string): string {
  const normalized = word.trim().toLowerCase() || "vocabulary";
  const lock = hashWord(normalized) % 100000;
  return `https://loremflickr.com/600/350/${encodeURIComponent(normalized)}?lock=${lock}`;
}

/**
 * Deterministic, always-available photo keyed by word seed. Used when the
 * keyword-relevant source is unavailable — still unique per word, never a
 * shared static image.
 */
export function getPicsumFallbackImageUrl(word: string): string {
  const normalized = word.trim().toLowerCase() || "vocabulary";
  return `https://picsum.photos/seed/${encodeURIComponent(normalized)}/600/350`;
}

/**
 * Detects image URLs generated by the old fixed 8-photo fallback pool
 * (`images.unsplash.com/photo-...?w=800&h=600&fit=crop&q=80&auto=format`).
 * Those photo IDs now 404 and were shared across many words, causing both
 * the "mất ảnh" and "trùng ảnh" bugs — treat them as stale so callers
 * regenerate a fresh, unique image instead of reusing them.
 */
export function isStalePresetFallbackUrl(url: string | null | undefined): boolean {
  const trimmed = url?.trim();
  if (!trimmed) return false;
  return (
    trimmed.includes("images.unsplash.com/photo-") &&
    trimmed.includes("w=800&h=600&fit=crop&q=80&auto=format")
  );
}

/**
 * Local, network-free illustration — the guaranteed last resort so a card
 * never shows a broken-image icon even if every remote image host is down.
 */
export function getDefaultLearningImageDataUrl(): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="350" viewBox="0 0 600 350">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stop-color="#262626"/>
        <stop offset="100%" stop-color="#404040"/>
      </linearGradient>
    </defs>
    <rect width="600" height="350" fill="url(#bg)"/>
    <g fill="#ffffff" opacity="0.95">
      <rect x="220" y="150" width="160" height="110" rx="10"/>
      <rect x="230" y="165" width="140" height="10" rx="4" fill="#737373"/>
      <rect x="230" y="185" width="110" height="8" rx="4" fill="#737373"/>
      <rect x="230" y="201" width="120" height="8" rx="4" fill="#737373"/>
      <rect x="230" y="217" width="90" height="8" rx="4" fill="#737373"/>
      <circle cx="300" cy="110" r="34" fill="#ffffff"/>
      <path d="M300 90 l40 18 -40 18 -40 -18 z" fill="#737373"/>
      <rect x="278" y="112" width="6" height="26" fill="#737373"/>
    </g>
  </svg>`;
  const base64 =
    typeof Buffer !== "undefined"
      ? Buffer.from(svg).toString("base64")
      : btoa(svg);
  return `data:image/svg+xml;base64,${base64}`;
}

/** Always returns a displayable image URL for a vocabulary word. */
export function resolveWordImageUrl(
  word: string,
  imageUrl?: string | null,
  searchKeyword?: string | null,
): string {
  const trimmed = imageUrl?.trim();
  if (trimmed && trimmed.startsWith("http")) return trimmed;
  const keyword = searchKeyword?.trim() || word;
  return getLoremFlickrImageUrl(keyword);
}

export async function searchPhotos(
  query: string,
  perPage = 1,
): Promise<UnsplashPhoto[]> {
  const accessKey = process.env.UNSPLASH_ACCESS_KEY;
  if (!accessKey) {
    throw new Error("UNSPLASH_ACCESS_KEY is not set");
  }

  const params = new URLSearchParams({
    query,
    per_page: String(perPage),
    orientation: "landscape",
  });

  const response = await fetch(
    `https://api.unsplash.com/search/photos?${params}`,
    {
      headers: {
        Authorization: `Client-ID ${accessKey}`,
      },
      next: { revalidate: 3600 },
    },
  );

  if (!response.ok) {
    throw new Error(`Unsplash API error: ${response.status}`);
  }

  const data = (await response.json()) as UnsplashSearchResponse;

  return data.results.map((photo) => ({
    id: photo.id,
    url: photo.urls.regular,
    alt: photo.alt_description ?? query,
    photographer: photo.user.name,
  }));
}

/**
 * Fetch word image via Unsplash API (if configured), then a deterministic,
 * keyword-relevant LoremFlickr photo unique to `searchKeyword` / `word`.
 * Never returns null.
 */
export async function fetchWordImageUrl(
  word: string,
  searchKeyword?: string | null,
): Promise<string> {
  const keyword =
    searchKeyword?.trim().toLowerCase() || word.trim().toLowerCase();
  if (!keyword) return getLoremFlickrImageUrl("vocabulary");

  if (process.env.UNSPLASH_ACCESS_KEY?.trim()) {
    try {
      const photos = await searchPhotos(keyword, 1);
      if (photos[0]?.url) return photos[0].url;
    } catch (error) {
      console.warn(`Unsplash API skipped for "${keyword}":`, error);
    }
  }

  return getLoremFlickrImageUrl(keyword);
}
