import {
  buildImageSearchQueries,
  isConcretePhrase,
} from "@/lib/image-keyword";

export type UnsplashPhoto = {
  id: string;
  url: string;
  alt: string;
  photographer: string;
};

type UnsplashSearchResponse = {
  results: Array<{
    id: string;
    alt_description: string | null;
    urls: { regular: string };
    user: { name: string };
  }>;
};

type OpenverseSearchResponse = {
  results?: Array<{
    id?: string;
    title?: string | null;
    description?: string | null;
    thumbnail?: string | null;
    tags?: Array<{ name?: string | null }>;
  }>;
};

type WikimediaSearchResponse = {
  query?: {
    pages?: Record<
      string,
      {
        title?: string;
        imageinfo?: Array<{
          thumburl?: string;
          url?: string;
          mime?: string;
          width?: number;
          height?: number;
        }>;
      }
    >;
  };
};

const GENERIC_QUERY_TOKENS = new Set([
  "action",
  "everyday",
  "moment",
  "object",
  "outdoors",
  "person",
  "photo",
  "photography",
  "scene",
]);

const SEMANTIC_IMAGE_VERSION = "7";

function hashWord(word: string): number {
  let hash = 0;
  for (const char of word.trim().toLowerCase()) {
    hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  }
  return hash;
}

/**
 * Keyword-relevant, unique-per-word photo. LoremFlickr sources a real photo
 * tagged with `word` from Flickr; `lock` pins it to one deterministic image
 * per word so the same card never shuffles between reloads.
 */
export function getLoremFlickrImageUrl(word: string): string {
  const normalized = word.trim().toLowerCase() || "vocabulary";
  const lock = hashWord(normalized) % 100000;
  return `https://loremflickr.com/600/350/${encodeURIComponent(normalized)}?lock=${lock}`;
}

/**
 * Deterministic, always-available photo keyed by word seed. Used when the
 * keyword-relevant source is unavailable — still unique per word, never a
 * shared static image.
 */
export function getPicsumFallbackImageUrl(word: string): string {
  const normalized = word.trim().toLowerCase() || "vocabulary";
  return `https://picsum.photos/seed/${encodeURIComponent(normalized)}/600/350`;
}

/**
 * Detects image URLs generated by the old fixed 8-photo fallback pool
 * (`images.unsplash.com/photo-...?w=800&h=600&fit=crop&q=80&auto=format`).
 * Those photo IDs now 404 and were shared across many words, causing both
 * the "mất ảnh" and "trùng ảnh" bugs — treat them as stale so callers
 * regenerate a fresh, unique image instead of reusing them.
 */
export function isStalePresetFallbackUrl(url: string | null | undefined): boolean {
  const trimmed = url?.trim();
  if (!trimmed) return false;
  return (
    trimmed.includes("images.unsplash.com/photo-") &&
    trimmed.includes("w=800&h=600&fit=crop&q=80&auto=format")
  );
}

/**
 * Random-photo providers cannot guarantee that the returned image depicts the
 * requested word. Treat their URLs as stale instead of presenting an unrelated
 * photo as learning content.
 */
export function isUntrustedRandomImageUrl(
  url: string | null | undefined,
): boolean {
  const trimmed = url?.trim();
  if (!trimmed) return false;
  try {
    const hostname = new URL(trimmed).hostname.toLowerCase();
    return (
      hostname === "loremflickr.com" ||
      hostname.endsWith(".loremflickr.com") ||
      hostname === "picsum.photos" ||
      hostname.endsWith(".picsum.photos")
    );
  } catch {
    return false;
  }
}

export function isOutdatedSemanticImageUrl(
  url: string | null | undefined,
): boolean {
  const trimmed = url?.trim();
  if (!trimmed) return false;
  try {
    const parsed = new URL(trimmed);
    const requiresSemanticVersion =
      parsed.hostname === "api.openverse.org" ||
      parsed.hostname === "images.unsplash.com" ||
      parsed.hostname === "upload.wikimedia.org";
    return (
      requiresSemanticVersion &&
      parsed.searchParams.get("semantic") !== SEMANTIC_IMAGE_VERSION
    );
  } catch {
    return false;
  }
}

export function isPlaceholderIllustrationUrl(
  url: string | null | undefined,
): boolean {
  return Boolean(url?.trim().startsWith("data:image/svg+xml"));
}

export function shouldRefreshImageUrl(
  url: string | null | undefined,
): boolean {
  return (
    !url?.trim() ||
    isStalePresetFallbackUrl(url) ||
    isUntrustedRandomImageUrl(url) ||
    isOutdatedSemanticImageUrl(url) ||
    isPlaceholderIllustrationUrl(url)
  );
}

/**
 * Local, word-specific illustration for concepts that stock photos cannot
 * represent reliably (especially prepositions and function words).
 */
export function getDefaultLearningImageDataUrl(
  word = "word",
  pos?: string | null,
): string {
  const normalizedWord =
    word.trim().toLowerCase().replace(/[^a-z0-9'-]/g, "") || "word";
  const safeWord = normalizedWord
    .toUpperCase()
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  const safePos = (pos?.trim().toUpperCase() || "VOCABULARY")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  const relationGraphic = (() => {
    if (["over", "above"].includes(normalizedWord)) {
      return `<rect x="230" y="205" width="140" height="22" rx="11"/><circle cx="300" cy="125" r="34"/><path d="M300 170v-24m-12 12 12-12 12 12" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>`;
    }
    if (["under", "below"].includes(normalizedWord)) {
      return `<rect x="230" y="95" width="140" height="22" rx="11"/><circle cx="300" cy="195" r="34"/><path d="M300 145v24m-12-12 12 12 12-12" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>`;
    }
    if (["in", "inside", "into"].includes(normalizedWord)) {
      return `<rect x="215" y="85" width="170" height="150" rx="20" fill="none" stroke="#fff" stroke-width="12"/><circle cx="300" cy="160" r="38"/>`;
    }
    if (["on", "upon"].includes(normalizedWord)) {
      return `<rect x="215" y="195" width="170" height="24" rx="12"/><circle cx="300" cy="151" r="36"/>`;
    }
    if (["near", "beside", "by", "with"].includes(normalizedWord)) {
      return `<circle cx="245" cy="160" r="42"/><rect x="330" y="118" width="84" height="84" rx="16"/><path d="M292 160h28" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round"/>`;
    }
    if (normalizedWord === "between") {
      return `<rect x="165" y="115" width="80" height="90" rx="16"/><circle cx="300" cy="160" r="36"/><rect x="355" y="115" width="80" height="90" rx="16"/>`;
    }
    if (["through", "across"].includes(normalizedWord)) {
      return `<circle cx="300" cy="160" r="72" fill="none" stroke="#fff" stroke-width="14"/><path d="M175 160h250m-28-24 28 24-28 24" fill="none" stroke="#fff" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>`;
    }
    if (normalizedWord === "too") {
      return `<rect x="175" y="205" width="250" height="14" rx="7" opacity=".6"/><rect x="205" y="165" width="42" height="40" rx="8"/><rect x="279" y="125" width="42" height="80" rx="8"/><rect x="353" y="70" width="42" height="135" rx="8"/><path d="M374 58l18 18m-18-18-18 18" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round"/>`;
    }
    if (pos?.toLowerCase() === "pronoun") {
      return `<circle cx="220" cy="125" r="30" opacity=".55"/><circle cx="300" cy="110" r="38"/><circle cx="380" cy="125" r="30" opacity=".55"/><path d="M170 220c8-50 34-72 50-72s42 22 50 72m-30 0c8-64 38-90 60-90s52 26 60 90m-30 0c8-50 34-72 50-72s42 22 50 72" fill="none" stroke="#fff" stroke-width="14" stroke-linecap="round" opacity=".9"/>`;
    }
    if (
      ["conjunction", "determiner", "article"].includes(
        pos?.toLowerCase() ?? "",
      )
    ) {
      return `<rect x="150" y="105" width="125" height="105" rx="18"/><rect x="325" y="105" width="125" height="105" rx="18"/><path d="M275 158h50" fill="none" stroke="#fff" stroke-width="12" stroke-linecap="round"/><circle cx="300" cy="158" r="12" fill="#6B7F5E"/>`;
    }
    return `<circle cx="230" cy="160" r="48"/><circle cx="370" cy="160" r="48" opacity=".65"/><path d="M284 160h66m-18-18 18 18-18 18" fill="none" stroke="#fff" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>`;
  })();

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="350" viewBox="0 0 600 350">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stop-color="#B8C7AE"/>
        <stop offset="100%" stop-color="#9CAF88"/>
      </linearGradient>
    </defs>
    <rect width="600" height="350" fill="url(#bg)"/>
    <rect x="24" y="22" width="128" height="30" rx="15" fill="#6B7F5E" opacity=".82"/>
    <text x="88" y="43" text-anchor="middle" font-family="Arial,sans-serif" font-size="13" font-weight="700" fill="#fff">${safePos}</text>
    <g fill="#ffffff" opacity="0.94">
      ${relationGraphic}
    </g>
    <text x="300" y="310" text-anchor="middle" font-family="Arial,sans-serif" font-size="34" font-weight="800" letter-spacing="3" fill="#fff">${safeWord}</text>
  </svg>`;
  const base64 =
    typeof Buffer !== "undefined"
      ? Buffer.from(svg).toString("base64")
      : btoa(svg);
  return `data:image/svg+xml;base64,${base64}`;
}

/** Always returns a displayable image URL for a vocabulary word. */
export function resolveWordImageUrl(
  word: string,
  imageUrl?: string | null,
  _searchKeyword?: string | null,
  pos?: string | null,
): string {
  void _searchKeyword;
  const trimmed = imageUrl?.trim();
  if (
    trimmed &&
    trimmed.startsWith("http") &&
    !isStalePresetFallbackUrl(trimmed) &&
    !isUntrustedRandomImageUrl(trimmed) &&
    !isOutdatedSemanticImageUrl(trimmed) &&
    !isPlaceholderIllustrationUrl(trimmed)
  ) {
    return trimmed;
  }
  return getDefaultLearningImageDataUrl(word, pos);
}

export async function searchPhotos(
  query: string,
  perPage = 1,
): Promise<UnsplashPhoto[]> {
  const accessKey = process.env.UNSPLASH_ACCESS_KEY;
  if (!accessKey) {
    throw new Error("UNSPLASH_ACCESS_KEY is not set");
  }

  const params = new URLSearchParams({
    query,
    per_page: String(perPage),
    orientation: "landscape",
  });

  const response = await fetch(
    `https://api.unsplash.com/search/photos?${params}`,
    {
      headers: {
        Authorization: `Client-ID ${accessKey}`,
      },
      next: { revalidate: 3600 },
    },
  );

  if (!response.ok) {
    throw new Error(`Unsplash API error: ${response.status}`);
  }

  const data = (await response.json()) as UnsplashSearchResponse;

  return data.results.map((photo) => ({
    id: photo.id,
    url: photo.urls.regular,
    alt: photo.alt_description ?? query,
    photographer: photo.user.name,
  }));
}

function semanticTokens(value: string): Set<string> {
  return new Set(
    value
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, " ")
      .split(/\s+/)
      .filter((token) => !GENERIC_QUERY_TOKENS.has(token))
      .map((token) => {
        if (token.endsWith("ing") && token.length > 5) {
          let stem = token.slice(0, -3);
          if (stem.at(-1) === stem.at(-2)) stem = stem.slice(0, -1);
          if (stem === "mak" || stem === "tak") stem += "e";
          return stem;
        }
        return token.replace(/(?:ies|es|s)$/, "");
      })
      .filter((token) => token.length > 2 && !GENERIC_QUERY_TOKENS.has(token)),
  );
}

function overlapCount(left: Set<string>, right: Set<string>): number {
  let count = 0;
  for (const token of left) {
    if (right.has(token)) count += 1;
  }
  return count;
}

function markSemanticImageUrl(url: string): string {
  const versionedUrl = new URL(url);
  versionedUrl.searchParams.set("semantic", SEMANTIC_IMAGE_VERSION);
  return versionedUrl.toString();
}

/**
 * Public-domain fallback with semantic validation. Openverse may return broad
 * full-text matches, so only accept a result whose title/tags overlap both the
 * vocabulary word and the concrete search phrase.
 */
export async function searchOpenversePhoto(
  word: string,
  query: string,
  requireWordMatch = true,
): Promise<string | null> {
  const params = new URLSearchParams({
    q: query,
    page_size: "20",
    license: "cc0,pdm",
    mature: "false",
    aspect_ratio: "wide",
  });

  try {
    const response = await fetch(
      `https://api.openverse.org/v1/images/?${params}`,
      {
        headers: { "User-Agent": "EnglishVocabApp/1.0" },
        next: { revalidate: 86400 },
      },
    );
    if (!response.ok) return null;

    const data = (await response.json()) as OpenverseSearchResponse;
    const wordTokens = semanticTokens(word);
    const queryTokens = semanticTokens(query);
    let best: { url: string; score: number } | null = null;

    for (const result of data.results ?? []) {
      const url = result.thumbnail?.trim();
      if (!url?.startsWith("https://")) continue;

      const titleTokens = semanticTokens(result.title ?? "");
      const metadataTokens = semanticTokens(
        [
          result.title,
          ...(result.tags ?? []).map((tag) => tag.name),
        ]
          .filter(Boolean)
          .join(" "),
      );
      if (
        requireWordMatch &&
        overlapCount(wordTokens, metadataTokens) === 0
      ) {
        continue;
      }

      const queryMatches = overlapCount(queryTokens, metadataTokens);
      const requiredMatches = queryTokens.size > 1 ? 2 : 1;
      if (queryMatches < requiredMatches) continue;

      const score =
        overlapCount(queryTokens, titleTokens) * 4 + queryMatches;
      if (!best || score > best.score) best = { url, score };
    }

    if (!best) return null;
    return markSemanticImageUrl(best.url);
  } catch {
    return null;
  }
}

const WIKIMEDIA_ALLOWED_MIME_TYPES = new Set(["image/jpeg", "image/png"]);
const WIKIMEDIA_MIN_WIDTH = 400;
const WIKIMEDIA_MIN_HEIGHT = 300;

/**
 * Wikimedia Commons has a much larger, keyless, generously-rate-limited photo
 * catalog than Openverse's CC0/PDM-only subset — useful as a second real-photo
 * fallback when Unsplash's quota is exhausted and Openverse has no match.
 * Results are still validated against the search phrase to avoid unrelated
 * full-text matches (e.g. TV show titles matching a bare word like "how").
 */
export async function searchWikimediaPhoto(
  word: string,
  query: string,
  requireWordMatch = true,
): Promise<string | null> {
  const params = new URLSearchParams({
    action: "query",
    format: "json",
    generator: "search",
    gsrnamespace: "6",
    gsrsearch: `${query} filetype:bitmap`,
    gsrlimit: "15",
    prop: "imageinfo",
    iiprop: "url|mime|size",
    iiurlwidth: "1080",
    origin: "*",
  });

  try {
    const response = await fetch(
      `https://commons.wikimedia.org/w/api.php?${params}`,
      {
        headers: { "User-Agent": "EnglishVocabApp/1.0 (education flashcards)" },
        next: { revalidate: 86400 },
      },
    );
    if (!response.ok) return null;

    const data = (await response.json()) as WikimediaSearchResponse;
    const pages = Object.values(data.query?.pages ?? {});
    const wordTokens = semanticTokens(word);
    const queryTokens = semanticTokens(query);
    let best: { url: string; score: number } | null = null;

    for (const page of pages) {
      const info = page.imageinfo?.[0];
      const url = info?.thumburl?.trim() || info?.url?.trim();
      if (!url?.startsWith("https://")) continue;
      if (!info?.mime || !WIKIMEDIA_ALLOWED_MIME_TYPES.has(info.mime)) continue;
      if (
        (info.width ?? 0) < WIKIMEDIA_MIN_WIDTH ||
        (info.height ?? 0) < WIKIMEDIA_MIN_HEIGHT
      ) {
        continue;
      }

      const titleTokens = semanticTokens(
        (page.title ?? "").replace(/^file:/i, "").replace(/\.[a-z0-9]+$/i, ""),
      );
      if (requireWordMatch && overlapCount(wordTokens, titleTokens) === 0) {
        continue;
      }

      const queryMatches = overlapCount(queryTokens, titleTokens);
      const requiredMatches = queryTokens.size > 1 ? 2 : 1;
      if (queryMatches < requiredMatches) continue;

      const score = queryMatches * 4;
      if (!best || score > best.score) best = { url, score };
    }

    if (!best) return null;
    return markSemanticImageUrl(best.url);
  } catch {
    return null;
  }
}

/**
 * Always prefer a real photo. Curated everyday scenes are used for abstract
 * words so image search can return a concrete picture instead of a random
 * mismatch. Local SVG is only used if every photo source fails.
 *
 * Unsplash's free-tier quota is very low (50 requests/hour, shared by every
 * visitor), so it is only tried once per word with the single best query to
 * avoid exhausting it on words that will fall through anyway. Openverse and
 * Wikimedia Commons are keyless with generous limits, so every query variant
 * (including shortened 2-3 word slices) is tried against them before giving
 * up and showing a local illustration.
 */
export async function fetchWordImageUrl(
  word: string,
  searchKeyword?: string | null,
  pos?: string | null,
): Promise<string> {
  const queries = buildImageSearchQueries(word, { searchKeyword, pos });
  if (queries.length === 0) return getDefaultLearningImageDataUrl(word, pos);

  if (process.env.UNSPLASH_ACCESS_KEY?.trim()) {
    try {
      const photos = await searchPhotos(queries[0], 1);
      if (photos[0]?.url) {
        return markSemanticImageUrl(photos[0].url);
      }
    } catch (error) {
      console.warn(`Unsplash API skipped for "${queries[0]}":`, error);
    }
  }

  // A multi-word scene description (curated or Gemini-provided) already
  // encodes a deliberate, concrete meaning, and the query-token overlap
  // check below confirms the photo actually matches that scene. Only a
  // bare single-word query — with no other semantic signal — needs the
  // word itself to also appear in the photo's metadata.
  for (const keyword of queries) {
    const requireWordMatch = !isConcretePhrase(keyword, word);
    const openverseUrl = await searchOpenversePhoto(
      word,
      keyword,
      requireWordMatch,
    );
    if (openverseUrl) return openverseUrl;
  }

  for (const keyword of queries) {
    const requireWordMatch = !isConcretePhrase(keyword, word);
    const wikimediaUrl = await searchWikimediaPhoto(
      word,
      keyword,
      requireWordMatch,
    );
    if (wikimediaUrl) return wikimediaUrl;
  }

  return getDefaultLearningImageDataUrl(word, pos);
}
