import {
  buildImageSearchQueries,
  hasCuratedVisualKeyword,
  isAbstractImagePos,
  isConcretePhrase,
} from "@/lib/image-keyword";
import {
  getConceptIllustrationDataUrl,
  isConceptIllustrationUrl,
  shouldUseConceptIllustration,
} from "@/lib/concept-illustration";
import { isUnsafeImageMetadata, isUnsafeImageUrl, shouldSkipEncyclopediaImage } from "@/lib/safe-image-metadata";
import { requiresSafeImageOnly } from "@/lib/safe-image-search";

export type UnsplashPhoto = {
  id: string;
  url: string;
  alt: string;
  photographer: string;
};

type UnsplashSearchResponse = {
  results: Array<{
    id: string;
    alt_description: string | null;
    urls: { regular: string };
    user: { name: string };
  }>;
};

type OpenverseSearchResponse = {
  results?: Array<{
    id?: string;
    title?: string | null;
    description?: string | null;
    url?: string | null;
    thumbnail?: string | null;
    creator?: string | null;
    foreign_landing_url?: string | null;
    tags?: Array<{ name?: string | null }>;
  }>;
};

type WikimediaSearchResponse = {
  query?: {
    pages?: Record<
      string,
      {
        title?: string;
        imageinfo?: Array<{
          thumburl?: string;
          url?: string;
          mime?: string;
          width?: number;
          height?: number;
        }>;
      }
    >;
  };
};

const WIKIMEDIA_USER_AGENT =
  "EnglishVocabApp/1.0 (education flashcards)";

const SKIP_WIKTIONARY_FILE =
  /coat of arms|royal arms|flag of|\blogo\b|\bicon\b|seal of|wordmark/i;

const WIKIDATA_SKIP_INSTANCE = new Set([
  "Q4167410", // Wikimedia disambiguation page
  "Q5", // human
  "Q101352", // family name
  "Q202444", // given name
  "Q215380", // band
  "Q482994", // album
  "Q11424", // film
  "Q5398426", // television series
  "Q43229", // organization
  "Q4830453", // business
  "Q783794", // company
]);

const GENERIC_QUERY_TOKENS = new Set([
  "action",
  "everyday",
  "moment",
  "object",
  "outdoors",
  "person",
  "photo",
  "photography",
  "scene",
]);

const SEMANTIC_IMAGE_VERSION = "14";

const DISPLAYABLE_IMAGE_HOSTS = [
  "images.unsplash.com",
  "upload.wikimedia.org",
  "images.pexels.com",
  "live.staticflickr.com",
];

function isDisplayableImageHost(hostname: string): boolean {
  const host = hostname.toLowerCase();
  return (
    DISPLAYABLE_IMAGE_HOSTS.includes(host) ||
    host.endsWith(".staticflickr.com")
  );
}

/** Openverse API proxy thumbs often 424 in the browser — never display them. */
export function isBrokenOpenverseProxyUrl(
  url: string | null | undefined,
): boolean {
  const trimmed = url?.trim();
  if (!trimmed) return false;
  try {
    const parsed = new URL(trimmed);
    return (
      parsed.hostname === "api.openverse.org" &&
      parsed.pathname.includes("/images/")
    );
  } catch {
    return false;
  }
}

function pickDisplayableMediaUrl(url?: string | null): string | null {
  const trimmed = url?.trim();
  if (!trimmed?.startsWith("https://")) return null;
  if (isBrokenOpenverseProxyUrl(trimmed)) return null;
  if (isUnsafeImageUrl(trimmed)) return null;
  try {
    const parsed = new URL(trimmed);
    if (!isDisplayableImageHost(parsed.hostname)) return null;
    const pathText = decodeURIComponent(parsed.pathname).replace(/[_-]+/g, " ");
    if (isUnsafeImageMetadata(pathText)) return null;
  } catch {
    return null;
  }
  return trimmed;
}

function pickOpenverseMediaUrl(result: {
  url?: string | null;
  thumbnail?: string | null;
}): string | null {
  for (const candidate of [result.url, result.thumbnail]) {
    const url = pickDisplayableMediaUrl(candidate);
    if (url) return url;
  }
  return null;
}

function hashWord(word: string): number {
  let hash = 0;
  for (const char of word.trim().toLowerCase()) {
    hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  }
  return hash;
}

/**
 * Keyword-relevant, unique-per-word photo. LoremFlickr sources a real photo
 * tagged with `word` from Flickr; `lock` pins it to one deterministic image
 * per word so the same card never shuffles between reloads.
 */
export function getLoremFlickrImageUrl(word: string): string {
  const normalized = word.trim().toLowerCase() || "vocabulary";
  const lock = hashWord(normalized) % 100000;
  return `https://loremflickr.com/600/350/${encodeURIComponent(normalized)}?lock=${lock}`;
}

/**
 * Deterministic, always-available photo keyed by word seed. Used when the
 * keyword-relevant source is unavailable — still unique per word, never a
 * shared static image.
 */
export function getPicsumFallbackImageUrl(word: string): string {
  const normalized = word.trim().toLowerCase() || "vocabulary";
  return `https://picsum.photos/seed/${encodeURIComponent(normalized)}/600/350`;
}

/**
 * Detects image URLs generated by the old fixed 8-photo fallback pool
 * (`images.unsplash.com/photo-...?w=800&h=600&fit=crop&q=80&auto=format`).
 * Those photo IDs now 404 and were shared across many words, causing both
 * the "mất ảnh" and "trùng ảnh" bugs — treat them as stale so callers
 * regenerate a fresh, unique image instead of reusing them.
 */
export function isStalePresetFallbackUrl(url: string | null | undefined): boolean {
  const trimmed = url?.trim();
  if (!trimmed) return false;
  return (
    trimmed.includes("images.unsplash.com/photo-") &&
    trimmed.includes("w=800&h=600&fit=crop&q=80&auto=format")
  );
}

/**
 * Random-photo providers cannot guarantee that the returned image depicts the
 * requested word. Treat their URLs as stale instead of presenting an unrelated
 * photo as learning content.
 */
export function isUntrustedRandomImageUrl(
  url: string | null | undefined,
): boolean {
  const trimmed = url?.trim();
  if (!trimmed) return false;
  try {
    const hostname = new URL(trimmed).hostname.toLowerCase();
    return (
      hostname === "loremflickr.com" ||
      hostname.endsWith(".loremflickr.com") ||
      hostname === "picsum.photos" ||
      hostname.endsWith(".picsum.photos")
    );
  } catch {
    return false;
  }
}

export function isOutdatedSemanticImageUrl(
  url: string | null | undefined,
): boolean {
  const trimmed = url?.trim();
  if (!trimmed) return false;
  try {
    const parsed = new URL(trimmed);
    const host = parsed.hostname.toLowerCase();
    const requiresSemanticVersion =
      host === "api.openverse.org" ||
      host === "images.unsplash.com" ||
      host === "upload.wikimedia.org" ||
      host === "images.pexels.com" ||
      host === "live.staticflickr.com" ||
      host.endsWith(".staticflickr.com");
    return (
      requiresSemanticVersion &&
      parsed.searchParams.get("semantic") !== SEMANTIC_IMAGE_VERSION
    );
  } catch {
    return false;
  }
}

/** Client display — accept real http photos even before semantic refresh completes. */
export function isDisplayableHttpImageUrl(
  url: string | null | undefined,
  word?: string | null,
): boolean {
  const trimmed = url?.trim();
  if (!trimmed?.startsWith("http")) return false;
  if (isUnsafeImageUrl(trimmed)) return false;
  if (word && requiresSafeImageOnly(word)) return false;
  if (isStalePresetFallbackUrl(trimmed)) return false;
  if (isUntrustedRandomImageUrl(trimmed)) return false;
  if (isPlaceholderIllustrationUrl(trimmed)) return false;
  if (isBrokenOpenverseProxyUrl(trimmed)) return false;
  if (isOutdatedSemanticImageUrl(trimmed)) return false;
  try {
    return isDisplayableImageHost(new URL(trimmed).hostname);
  } catch {
    return false;
  }
}

export function isPlaceholderIllustrationUrl(
  url: string | null | undefined,
): boolean {
  const trimmed = url?.trim();
  if (!trimmed?.startsWith("data:image/svg+xml")) return false;
  return !isConceptIllustrationUrl(trimmed);
}

export function shouldRefreshImageUrl(
  url: string | null | undefined,
  word?: string | null,
  pos?: string | null,
): boolean {
  const trimmed = url?.trim();
  if (word && shouldUseConceptIllustration(word, pos)) {
    return !isConceptIllustrationUrl(trimmed);
  }
  if (word && requiresSafeImageOnly(word)) {
    return !trimmed || trimmed.startsWith("http") || isUnsafeImageUrl(trimmed);
  }
  if (!trimmed) return true;
  if (isUnsafeImageUrl(trimmed)) return true;
  if (trimmed.startsWith("http") && !isDisplayableHttpImageUrl(trimmed, word)) {
    return true;
  }
  return (
    isStalePresetFallbackUrl(trimmed) ||
    isUntrustedRandomImageUrl(trimmed) ||
    isOutdatedSemanticImageUrl(trimmed) ||
    isPlaceholderIllustrationUrl(trimmed) ||
    isBrokenOpenverseProxyUrl(trimmed)
  );
}

/**
 * Local, word-specific illustration for concepts that stock photos cannot
 * represent reliably (especially prepositions and function words).
 */
export function getDefaultLearningImageDataUrl(
  word = "word",
  pos?: string | null,
): string {
  if (shouldUseConceptIllustration(word, pos)) {
    return getConceptIllustrationDataUrl(word, pos);
  }
  const normalizedWord =
    word.trim().toLowerCase().replace(/[^a-z0-9'-]/g, "") || "word";
  const safeWord = normalizedWord
    .toUpperCase()
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  const safePos = (pos?.trim().toUpperCase() || "VOCABULARY")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  const relationGraphic = (() => {
    if (["over", "above"].includes(normalizedWord)) {
      return `<rect x="230" y="205" width="140" height="22" rx="11"/><circle cx="300" cy="125" r="34"/><path d="M300 170v-24m-12 12 12-12 12 12" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>`;
    }
    if (["under", "below"].includes(normalizedWord)) {
      return `<rect x="230" y="95" width="140" height="22" rx="11"/><circle cx="300" cy="195" r="34"/><path d="M300 145v24m-12-12 12 12 12-12" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>`;
    }
    if (["in", "inside", "into"].includes(normalizedWord)) {
      return `<rect x="215" y="85" width="170" height="150" rx="20" fill="none" stroke="#fff" stroke-width="12"/><circle cx="300" cy="160" r="38"/>`;
    }
    if (["on", "upon"].includes(normalizedWord)) {
      return `<rect x="215" y="195" width="170" height="24" rx="12"/><circle cx="300" cy="151" r="36"/>`;
    }
    if (["near", "beside", "by", "with"].includes(normalizedWord)) {
      return `<circle cx="245" cy="160" r="42"/><rect x="330" y="118" width="84" height="84" rx="16"/><path d="M292 160h28" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round"/>`;
    }
    if (normalizedWord === "between") {
      return `<rect x="165" y="115" width="80" height="90" rx="16"/><circle cx="300" cy="160" r="36"/><rect x="355" y="115" width="80" height="90" rx="16"/>`;
    }
    if (["through", "across"].includes(normalizedWord)) {
      return `<circle cx="300" cy="160" r="72" fill="none" stroke="#fff" stroke-width="14"/><path d="M175 160h250m-28-24 28 24-28 24" fill="none" stroke="#fff" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>`;
    }
    if (normalizedWord === "too") {
      return `<rect x="175" y="205" width="250" height="14" rx="7" opacity=".6"/><rect x="205" y="165" width="42" height="40" rx="8"/><rect x="279" y="125" width="42" height="80" rx="8"/><rect x="353" y="70" width="42" height="135" rx="8"/><path d="M374 58l18 18m-18-18-18 18" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round"/>`;
    }
    if (pos?.toLowerCase() === "pronoun") {
      return `<circle cx="220" cy="125" r="30" opacity=".55"/><circle cx="300" cy="110" r="38"/><circle cx="380" cy="125" r="30" opacity=".55"/><path d="M170 220c8-50 34-72 50-72s42 22 50 72m-30 0c8-64 38-90 60-90s52 26 60 90m-30 0c8-50 34-72 50-72s42 22 50 72" fill="none" stroke="#fff" stroke-width="14" stroke-linecap="round" opacity=".9"/>`;
    }
    if (
      ["conjunction", "determiner", "article"].includes(
        pos?.toLowerCase() ?? "",
      )
    ) {
      return `<rect x="150" y="105" width="125" height="105" rx="18"/><rect x="325" y="105" width="125" height="105" rx="18"/><path d="M275 158h50" fill="none" stroke="#fff" stroke-width="12" stroke-linecap="round"/><circle cx="300" cy="158" r="12" fill="#F97316"/>`;
    }
    return `<circle cx="230" cy="160" r="48"/><circle cx="370" cy="160" r="48" opacity=".65"/><path d="M284 160h66m-18-18 18 18-18 18" fill="none" stroke="#fff" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>`;
  })();

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="350" viewBox="0 0 600 350">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stop-color="#60A5FA"/>
        <stop offset="55%" stop-color="#2563EB"/>
        <stop offset="100%" stop-color="#F97316"/>
      </linearGradient>
    </defs>
    <rect width="600" height="350" fill="url(#bg)"/>
    <rect x="24" y="22" width="128" height="30" rx="15" fill="#1D4ED8" opacity=".88"/>
    <text x="88" y="43" text-anchor="middle" font-family="Arial,sans-serif" font-size="13" font-weight="700" fill="#fff">${safePos}</text>
    <g fill="#ffffff" opacity="0.94">
      ${relationGraphic}
    </g>
    <text x="300" y="310" text-anchor="middle" font-family="Arial,sans-serif" font-size="34" font-weight="800" letter-spacing="3" fill="#fff">${safeWord}</text>
  </svg>`;
  const base64 =
    typeof Buffer !== "undefined"
      ? Buffer.from(svg).toString("base64")
      : btoa(svg);
  return `data:image/svg+xml;base64,${base64}`;
}

/** Always returns a displayable image URL for a vocabulary word. */
export function resolveWordImageUrl(
  word: string,
  imageUrl?: string | null,
  _searchKeyword?: string | null,
  pos?: string | null,
): string {
  void _searchKeyword;
  if (requiresSafeImageOnly(word) || shouldUseConceptIllustration(word, pos)) {
    return getConceptIllustrationDataUrl(word, pos);
  }
  const trimmed = imageUrl?.trim();
  if (isDisplayableHttpImageUrl(trimmed, word)) {
    return trimmed!;
  }
  return getDefaultLearningImageDataUrl(word, pos);
}

type PexelsSearchResponse = {
  photos?: Array<{
    alt?: string | null;
    photographer?: string | null;
    src?: { large?: string; landscape?: string };
  }>;
};

async function searchPexelsPhotos(
  query: string,
): Promise<Array<{ url: string; alt: string }>> {
  const apiKey = process.env.PEXELS_API_KEY?.trim();
  if (!apiKey) return [];

  const params = new URLSearchParams({
    query,
    per_page: "8",
    orientation: "landscape",
  });

  try {
    const response = await fetch(`https://api.pexels.com/v1/search?${params}`, {
      headers: { Authorization: apiKey },
      next: { revalidate: 3600 },
    });
    if (!response.ok) return [];
    const data = (await response.json()) as PexelsSearchResponse;
    return (data.photos ?? [])
      .map((photo) => ({
        url: pickDisplayableMediaUrl(photo.src?.landscape) ??
          pickDisplayableMediaUrl(photo.src?.large) ??
          "",
        alt: photo.alt ?? query,
      }))
      .filter((photo) => photo.url);
  } catch {
    return [];
  }
}

async function pickScoredStockPhoto(
  word: string,
  query: string,
  photos: Array<{ url: string; alt: string; extra?: string }>,
): Promise<string | null> {
  let best: { url: string; score: number } | null = null;
  for (const photo of photos) {
    if (isUnsafeImageMetadata(photo.alt, photo.extra, query)) continue;
    if (!photo.url || isUnsafeImageUrl(photo.url)) continue;
    const score = scoreImageMetadata(word, query, photo.alt);
    if (score <= 0) continue;
    const versioned = markSemanticImageUrl(photo.url);
    if (!isDisplayableHttpImageUrl(versioned, word)) continue;
    if (!best || score > best.score) best = { url: versioned, score };
  }
  return best?.url ?? null;
}

export async function searchPhotos(
  query: string,
  perPage = 1,
): Promise<UnsplashPhoto[]> {
  const accessKey = process.env.UNSPLASH_ACCESS_KEY;
  if (!accessKey) {
    throw new Error("UNSPLASH_ACCESS_KEY is not set");
  }

  const params = new URLSearchParams({
    query,
    per_page: String(perPage),
    orientation: "landscape",
    content_filter: "high",
  });

  const response = await fetch(
    `https://api.unsplash.com/search/photos?${params}`,
    {
      headers: {
        Authorization: `Client-ID ${accessKey}`,
      },
      next: { revalidate: 3600 },
    },
  );

  if (!response.ok) {
    throw new Error(`Unsplash API error: ${response.status}`);
  }

  const data = (await response.json()) as UnsplashSearchResponse;

  return data.results.map((photo) => ({
    id: photo.id,
    url: photo.urls.regular,
    alt: photo.alt_description ?? query,
    photographer: photo.user.name,
  }));
}

function semanticTokens(value: string): Set<string> {
  return new Set(
    value
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, " ")
      .split(/\s+/)
      .filter((token) => !GENERIC_QUERY_TOKENS.has(token))
      .map((token) => {
        if (token.endsWith("ing") && token.length > 5) {
          let stem = token.slice(0, -3);
          if (stem.at(-1) === stem.at(-2)) stem = stem.slice(0, -1);
          if (stem === "mak" || stem === "tak") stem += "e";
          return stem;
        }
        return token.replace(/(?:ies|es|s)$/, "");
      })
      .filter((token) => token.length > 2 && !GENERIC_QUERY_TOKENS.has(token)),
  );
}

function overlapCount(left: Set<string>, right: Set<string>): number {
  let count = 0;
  for (const token of left) {
    if (right.has(token)) count += 1;
  }
  return count;
}

function queryCoversWord(wordTokens: Set<string>, queryTokens: Set<string>): boolean {
  return overlapCount(wordTokens, queryTokens) > 0;
}

function queryOverlapScore(
  queryTokens: Set<string>,
  metaTokens: Set<string>,
  queryMatches: number,
): number {
  if (queryMatches === 0) return 0;
  const requiredMatches = queryTokens.size > 1 ? 2 : 1;
  if (queryMatches < requiredMatches) {
    const focus = [...queryTokens].at(-1);
    if (!focus || focus.length < 4 || !metaTokens.has(focus)) return 0;
  }
  return queryMatches * 2;
}

/** >0 only when photo metadata actually mentions the word or the search phrase. */
export function scoreImageMetadata(
  word: string,
  query: string,
  metadata: string,
): number {
  const wordTokens = semanticTokens(word);
  const queryTokens = semanticTokens(query);
  const metaTokens = semanticTokens(metadata);
  if (metaTokens.size === 0) return 0;

  const wordMatches = overlapCount(wordTokens, metaTokens);
  const queryMatches = overlapCount(queryTokens, metaTokens);
  if (wordMatches === 0 && queryMatches === 0) return 0;

  // Scene queries ("thumbs up" for "good") must match the scene, not the
  // English word — otherwise book titles / homonyms win (Why, water well).
  if (!queryCoversWord(wordTokens, queryTokens)) {
    if (isUngroundedSingleTokenQuery(wordTokens, queryTokens)) return 0;
    return queryOverlapScore(queryTokens, metaTokens, queryMatches);
  }

  if (isUngroundedSingleTokenQuery(wordTokens, queryTokens) && wordMatches === 0) {
    return 0;
  }

  const requiredMatches = queryTokens.size > 1 ? 2 : 1;
  if (queryMatches < requiredMatches && wordMatches === 0) {
    const focus = [...queryTokens].at(-1);
    if (!focus || focus.length < 4 || !metaTokens.has(focus)) return 0;
  }
  return wordMatches * 5 + queryMatches * 2;
}

/**
 * A multi-word query phrase like "brown everyday scene" or "person
 * shivering" collapses to a single meaningful token once generic words
 * ("everyday", "scene", "person") are filtered out — "brown" and "shiver"
 * respectively. That lone token is safe to match on its own only when it
 * *is* the vocabulary word itself ("brown" for the word "brown"): then a
 * title match is exactly a literal-word match, which is always trustworthy.
 * When the lone token is an unrelated proxy for an abstract word ("shiver"
 * for "rather"), a single coincidental match (e.g. a product named
 * "Shiver") is not enough evidence — that case must additionally require
 * the literal word to appear in the metadata, which it never will for a
 * generated proxy phrase, correctly failing this query variant closed so
 * the caller tries a more specific fallback instead.
 */
function isUngroundedSingleTokenQuery(
  wordTokens: Set<string>,
  queryTokens: Set<string>,
): boolean {
  return queryTokens.size === 1 && overlapCount(wordTokens, queryTokens) === 0;
}

/** Tags are too noisy (e.g. a jet tagged "lion"). The title must carry the word or enough of the query. */
function titleSupportsQuery(
  wordTokens: Set<string>,
  queryTokens: Set<string>,
  titleTokens: Set<string>,
): boolean {
  if (overlapCount(wordTokens, titleTokens) > 0) return true;
  const needed = queryTokens.size > 1 ? 2 : 1;
  return overlapCount(queryTokens, titleTokens) >= needed;
}

function markSemanticImageUrl(url: string): string {
  const versionedUrl = new URL(url);
  versionedUrl.searchParams.set("semantic", SEMANTIC_IMAGE_VERSION);
  return versionedUrl.toString();
}

/**
 * Public-domain fallback with semantic validation. Openverse may return broad
 * full-text matches, so only accept a result whose title/tags overlap both the
 * vocabulary word and the concrete search phrase.
 */
export async function searchOpenversePhoto(
  word: string,
  query: string,
  requireWordMatch = true,
): Promise<string | null> {
  const params = new URLSearchParams({
    q: query,
    page_size: "20",
    license: "cc0,pdm",
    mature: "false",
    aspect_ratio: "wide",
  });

  try {
    const response = await fetch(
      `https://api.openverse.org/v1/images/?${params}`,
      {
        headers: { "User-Agent": "EnglishVocabApp/1.0" },
        next: { revalidate: 86400 },
      },
    );
    if (!response.ok) return null;

    const data = (await response.json()) as OpenverseSearchResponse;
    const wordTokens = semanticTokens(word);
    const queryTokens = semanticTokens(query);
    const effectiveRequireWordMatch =
      requireWordMatch || isUngroundedSingleTokenQuery(wordTokens, queryTokens);
    let best: { url: string; score: number } | null = null;

    for (const result of data.results ?? []) {
      const url = pickOpenverseMediaUrl(result);
      if (!url) continue;

      const metadataText = [
        result.title,
        result.description,
        result.creator,
        result.foreign_landing_url,
        result.url,
        result.thumbnail,
        ...(result.tags ?? []).map((tag) => tag.name),
      ]
        .filter(Boolean)
        .join(" ");
      if (isUnsafeImageMetadata(metadataText)) continue;
      if (isUnsafeImageUrl(result.url) || isUnsafeImageUrl(result.foreign_landing_url)) {
        continue;
      }

      const titleTokens = semanticTokens(result.title ?? "");
      const metadataTokens = semanticTokens(
        [
          result.title,
          ...(result.tags ?? []).map((tag) => tag.name),
        ]
          .filter(Boolean)
          .join(" "),
      );
      if (
        effectiveRequireWordMatch &&
        overlapCount(wordTokens, metadataTokens) === 0
      ) {
        continue;
      }
      if (!titleSupportsQuery(wordTokens, queryTokens, titleTokens)) continue;

      const queryMatches = overlapCount(queryTokens, metadataTokens);
      const requiredMatches = queryTokens.size > 1 ? 2 : 1;
      if (queryMatches < requiredMatches) continue;

      const score =
        overlapCount(queryTokens, titleTokens) * 4 + queryMatches;
      if (!best || score > best.score) best = { url, score };
    }

    if (!best) return null;
    return markSemanticImageUrl(best.url);
  } catch {
    return null;
  }
}

const WIKIMEDIA_ALLOWED_MIME_TYPES = new Set([
  "image/jpeg",
  "image/png",
  "image/svg+xml",
]);
const WIKIMEDIA_MIN_WIDTH = 240;
const WIKIMEDIA_MIN_HEIGHT = 180;

/**
 * Wikimedia Commons has a much larger, keyless, generously-rate-limited photo
 * catalog than Openverse's CC0/PDM-only subset — useful as a second real-photo
 * fallback when Unsplash's quota is exhausted and Openverse has no match.
 * Results are still validated against the search phrase to avoid unrelated
 * full-text matches (e.g. TV show titles matching a bare word like "how").
 */
export async function searchWikimediaPhoto(
  word: string,
  query: string,
  requireWordMatch = true,
): Promise<string | null> {
  const params = new URLSearchParams({
    action: "query",
    format: "json",
    generator: "search",
    gsrnamespace: "6",
    gsrsearch: query,
    gsrlimit: "15",
    prop: "imageinfo",
    iiprop: "url|mime|size",
    iiurlwidth: "1080",
    origin: "*",
  });

  try {
    const response = await fetch(
      `https://commons.wikimedia.org/w/api.php?${params}`,
      {
        headers: { "User-Agent": "EnglishVocabApp/1.0 (education flashcards)" },
        next: { revalidate: 86400 },
      },
    );
    if (!response.ok) return null;

    const data = (await response.json()) as WikimediaSearchResponse;
    const pages = Object.values(data.query?.pages ?? {});
    const wordTokens = semanticTokens(word);
    const queryTokens = semanticTokens(query);
    const effectiveRequireWordMatch =
      requireWordMatch || isUngroundedSingleTokenQuery(wordTokens, queryTokens);
    let best: { url: string; score: number } | null = null;

    for (const page of pages) {
      const info = page.imageinfo?.[0];
      const url =
        pickDisplayableMediaUrl(info?.thumburl) ||
        pickDisplayableMediaUrl(info?.url);
      if (!url) continue;
      if (!info?.mime || !WIKIMEDIA_ALLOWED_MIME_TYPES.has(info.mime)) continue;
      if (info.mime === "image/svg+xml" && !info.thumburl) continue;
      if (
        (info.width ?? 0) < WIKIMEDIA_MIN_WIDTH ||
        (info.height ?? 0) < WIKIMEDIA_MIN_HEIGHT
      ) {
        continue;
      }

      const titleText = (page.title ?? "").replace(/^file:/i, "");
      if (isUnsafeImageMetadata(titleText, url)) continue;
      if (/\bstamp of\b|\bpostage stamp\b|\.pdf$/i.test(titleText)) continue;

      const titleTokens = semanticTokens(
        titleText.replace(/\.[a-z0-9]+$/i, ""),
      );
      if (
        effectiveRequireWordMatch &&
        overlapCount(wordTokens, titleTokens) === 0
      ) {
        continue;
      }
      if (!titleSupportsQuery(wordTokens, queryTokens, titleTokens)) continue;

      const queryMatches = overlapCount(queryTokens, titleTokens);
      const requiredMatches = queryTokens.size > 1 ? 2 : 1;
      if (queryMatches < requiredMatches) continue;

      const score = queryMatches * 4;
      if (!best || score > best.score) best = { url, score };
    }

    if (!best) return null;
    return markSemanticImageUrl(best.url);
  } catch {
    return null;
  }
}

type WikipediaSummaryResponse = {
  type?: string;
  title?: string;
  thumbnail?: { source?: string };
  originalimage?: { source?: string };
};

function cleanMediaUrl(url: string): string {
  try {
    const parsed = new URL(url);
    parsed.searchParams.delete("utm_source");
    return parsed.toString();
  } catch {
    return url;
  }
}

/**
 * Wikipedia article lead image — reliable for school nouns (fraction, vowel,
 * triangle) when stock-photo APIs miss diagrams and objects.
 */
export async function searchWikipediaLeadImage(
  word: string,
): Promise<string | null> {
  const normalized = word.trim();
  if (!normalized) return null;
  if (shouldSkipEncyclopediaImage(normalized)) return null;

  try {
    const response = await fetch(
      `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(normalized)}`,
      {
        headers: {
          "User-Agent": "EnglishVocabApp/1.0 (education flashcards)",
          Accept: "application/json",
        },
        next: { revalidate: 86400 },
      },
    );
    if (!response.ok) return null;
    const data = (await response.json()) as WikipediaSummaryResponse;
    if (data.type !== "disambiguation") {
      const leadTitle = (data.title ?? "")
        .replace(/\s*\([^)]*\)\s*/g, "")
        .trim()
        .toLowerCase();
      if (
        leadTitle === normalized.toLowerCase() &&
        !isUnsafeImageMetadata(data.title)
      ) {
        const url = pickDisplayableMediaUrl(
          data.originalimage?.source ?? data.thumbnail?.source,
        );
        if (url) return markSemanticImageUrl(cleanMediaUrl(url));
      }
    }

    const searchParams = new URLSearchParams({
      action: "query",
      format: "json",
      generator: "search",
      gsrsearch: normalized,
      gsrlimit: "8",
      gsrnamespace: "0",
      prop: "pageimages",
      piprop: "thumbnail",
      pithumbsize: "1080",
      origin: "*",
      redirects: "1",
    });
    const searchResponse = await fetch(
      `https://en.wikipedia.org/w/api.php?${searchParams}`,
      {
        headers: {
          "User-Agent": "EnglishVocabApp/1.0 (education flashcards)",
        },
        next: { revalidate: 86400 },
      },
    );
    if (!searchResponse.ok) return null;
    const searchData = (await searchResponse.json()) as {
      query?: {
        pages?: Record<
          string,
          { title?: string; index?: number; thumbnail?: { source?: string } }
        >;
      };
    };
    const wordTokens = semanticTokens(normalized);
    const pages = Object.values(searchData.query?.pages ?? {}).sort(
      (left, right) => (left.index ?? 99) - (right.index ?? 99),
    );
    for (const page of pages) {
      const title = page.title ?? "";
      if (/disambiguation/i.test(title)) continue;
      if (isUnsafeImageMetadata(title)) continue;
      const url = pickDisplayableMediaUrl(page.thumbnail?.source);
      if (!url) continue;
      const titleTokens = semanticTokens(title.replace(/\([^)]*\)/g, ""));
      if (overlapCount(wordTokens, titleTokens) === 0) continue;
      const cleanedTitle = title.replace(/\s*\([^)]*\)\s*/g, "").trim().toLowerCase();
      if (cleanedTitle !== normalized.toLowerCase()) continue;
      return markSemanticImageUrl(cleanMediaUrl(url));
    }
    return null;
  } catch {
    return null;
  }
}

async function resolveCommonsFileUrl(fileName: string): Promise<string | null> {
  const title = fileName.replace(/^File:/i, "").trim();
  if (!title) return null;
  if (SKIP_WIKTIONARY_FILE.test(title.replace(/[_-]+/g, " "))) return null;

  const params = new URLSearchParams({
    action: "query",
    format: "json",
    titles: `File:${title}`,
    prop: "imageinfo",
    iiprop: "url|mime|size",
    iiurlwidth: "1080",
    origin: "*",
  });

  try {
    const response = await fetch(
      `https://commons.wikimedia.org/w/api.php?${params}`,
      {
        headers: { "User-Agent": WIKIMEDIA_USER_AGENT },
        next: { revalidate: 86400 },
      },
    );
    if (!response.ok) return null;
    const data = (await response.json()) as WikimediaSearchResponse;
    const page = Object.values(data.query?.pages ?? {})[0];
    const info = page?.imageinfo?.[0];
    const url =
      pickDisplayableMediaUrl(info?.thumburl) ||
      pickDisplayableMediaUrl(info?.url);
    if (!url) return null;
    if (!info?.mime || !WIKIMEDIA_ALLOWED_MIME_TYPES.has(info.mime)) return null;
    if (info.mime === "image/svg+xml") return null;
    if (
      (info.width ?? 0) < WIKIMEDIA_MIN_WIDTH ||
      (info.height ?? 0) < WIKIMEDIA_MIN_HEIGHT
    ) {
      return null;
    }
    if (isUnsafeImageMetadata(title, url)) return null;
    return markSemanticImageUrl(cleanMediaUrl(url));
  } catch {
    return null;
  }
}

type WiktionaryMediaList = {
  items?: Array<{
    type?: string;
    title?: string;
    caption?: { text?: string | null };
  }>;
};

/**
 * Dictionary-page illustration — lexicographers pick a photo of the primary
 * sense (apple → a red apple). Stronger than keyword search for concrete nouns.
 */
export async function searchWiktionaryIllustration(
  word: string,
): Promise<string | null> {
  const normalized = word.trim();
  if (!normalized) return null;
  if (shouldSkipEncyclopediaImage(normalized)) return null;

  try {
    const response = await fetch(
      `https://en.wiktionary.org/api/rest_v1/page/media-list/${encodeURIComponent(normalized)}`,
      {
        headers: {
          "User-Agent": WIKIMEDIA_USER_AGENT,
          Accept: "application/json",
        },
        next: { revalidate: 86400 },
      },
    );
    if (!response.ok) return null;
    const data = (await response.json()) as WiktionaryMediaList;
    for (const item of data.items ?? []) {
      if (item.type !== "image" || !item.title) continue;
      const caption = item.caption?.text ?? "";
      if (isUnsafeImageMetadata(item.title, caption)) continue;
      const url = await resolveCommonsFileUrl(item.title);
      if (url) return url;
    }
    return null;
  } catch {
    return null;
  }
}

type WikidataEntitiesResponse = {
  entities?: Record<
    string,
    {
      descriptions?: { en?: { value?: string } };
      claims?: {
        P18?: Array<{ mainsnak?: { datavalue?: { value?: string } } }>;
        P31?: Array<{
          mainsnak?: { datavalue?: { value?: { id?: string } } };
        }>;
      };
    }
  >;
};

type WikipediaPagePropsResponse = {
  query?: {
    pages?: Record<
      string,
      {
        title?: string;
        missing?: boolean;
        pageprops?: { wikibase_item?: string };
      }
    >;
  };
};

/**
 * Wikidata P18 — the concept photo for the English Wikipedia article of this
 * word (lion → a lion, hole → a hole in wood). Skips people, bands, and
 * disambiguation pages.
 */
export async function searchWikidataConceptImage(
  word: string,
): Promise<string | null> {
  const normalized = word.trim();
  if (!normalized) return null;
  if (shouldSkipEncyclopediaImage(normalized)) return null;

  try {
    const wikiParams = new URLSearchParams({
      action: "query",
      format: "json",
      titles: normalized,
      redirects: "1",
      prop: "pageprops",
      ppprop: "wikibase_item",
      origin: "*",
    });
    const wikiResponse = await fetch(
      `https://en.wikipedia.org/w/api.php?${wikiParams}`,
      {
        headers: { "User-Agent": WIKIMEDIA_USER_AGENT },
        next: { revalidate: 86400 },
      },
    );
    if (!wikiResponse.ok) return null;
    const wikiData = (await wikiResponse.json()) as WikipediaPagePropsResponse;
    const page = Object.values(wikiData.query?.pages ?? {})[0];
    const qid = page?.pageprops?.wikibase_item;
    if (!qid || page?.missing) return null;

    const entityParams = new URLSearchParams({
      action: "wbgetentities",
      ids: qid,
      props: "claims|descriptions",
      languages: "en",
      format: "json",
      origin: "*",
    });
    const entityResponse = await fetch(
      `https://www.wikidata.org/w/api.php?${entityParams}`,
      {
        headers: { "User-Agent": WIKIMEDIA_USER_AGENT },
        next: { revalidate: 86400 },
      },
    );
    if (!entityResponse.ok) return null;
    const entityData = (await entityResponse.json()) as WikidataEntitiesResponse;
    const entity = entityData.entities?.[qid];
    const instanceIds = (entity?.claims?.P31 ?? [])
      .map((claim) => claim.mainsnak?.datavalue?.value?.id)
      .filter((id): id is string => Boolean(id));
    if (instanceIds.some((id) => WIKIDATA_SKIP_INSTANCE.has(id))) return null;

    const description = entity?.descriptions?.en?.value ?? "";
    if (
      /(?:family name|given name|disambiguation|album|film|band|company|municipality|surname)/i.test(
        description,
      )
    ) {
      return null;
    }

    const fileName = entity?.claims?.P18?.[0]?.mainsnak?.datavalue?.value;
    if (!fileName) return null;
    return resolveCommonsFileUrl(fileName);
  } catch {
    return null;
  }
}

/**
 * Concrete nouns can use dictionary photos (apple, lion). Abstract POS and
 * homonyms (well the adverb, domestic = nội địa) must search a scene phrase
 * instead — Wiktionary/Wikipedia pick the encyclopedia sense.
 * Then Unsplash / optional Pexels, Wikimedia Commons, Openverse.
 */
export async function fetchWordImageUrl(
  word: string,
  searchKeyword?: string | null,
  pos?: string | null,
): Promise<string> {
  if (requiresSafeImageOnly(word) || shouldUseConceptIllustration(word, pos)) {
    return getConceptIllustrationDataUrl(word, pos);
  }
  const queries = buildImageSearchQueries(word, { searchKeyword, pos });
  if (queries.length === 0) return getDefaultLearningImageDataUrl(word, pos);
  const primaryQuery = queries[0];

  if (!isAbstractImagePos(pos)) {
    const wiktionaryUrl = await searchWiktionaryIllustration(word);
    if (wiktionaryUrl && isDisplayableHttpImageUrl(wiktionaryUrl, word)) {
      return wiktionaryUrl;
    }
    const wikidataUrl = await searchWikidataConceptImage(word);
    if (wikidataUrl && isDisplayableHttpImageUrl(wikidataUrl, word)) {
      return wikidataUrl;
    }
  }

  if (process.env.UNSPLASH_ACCESS_KEY?.trim()) {
    try {
      const photos = await searchPhotos(primaryQuery, 8);
      const unsplashUrl = await pickScoredStockPhoto(
        word,
        primaryQuery,
        photos.map((photo) => ({
          url: photo.url,
          alt: photo.alt,
          extra: photo.photographer,
        })),
      );
      if (unsplashUrl) return unsplashUrl;
    } catch (error) {
      console.warn(`Unsplash API skipped for "${primaryQuery}":`, error);
    }
  }

  const pexelsPhotos = await searchPexelsPhotos(primaryQuery);
  const pexelsUrl = await pickScoredStockPhoto(word, primaryQuery, pexelsPhotos);
  if (pexelsUrl) return pexelsUrl;

  // Wikimedia titles are usually literal ("Lion at Wild Animal Sanctuary").
  // Openverse tags are noisier and used to win with jets tagged "lion".
  for (const keyword of queries) {
    const requireWordMatch = !isConcretePhrase(keyword, word);
    const wikimediaUrl = await searchWikimediaPhoto(
      word,
      keyword,
      requireWordMatch,
    );
    if (wikimediaUrl && isDisplayableHttpImageUrl(wikimediaUrl, word)) {
      return wikimediaUrl;
    }
  }

  for (const keyword of queries) {
    const requireWordMatch = !isConcretePhrase(keyword, word);
    const openverseUrl = await searchOpenversePhoto(
      word,
      keyword,
      requireWordMatch,
    );
    if (openverseUrl && isDisplayableHttpImageUrl(openverseUrl, word)) {
      return openverseUrl;
    }
  }

  const wikipediaUrl =
    shouldSkipEncyclopediaImage(word) ||
    isAbstractImagePos(pos) ||
    hasCuratedVisualKeyword(word)
      ? null
      : await searchWikipediaLeadImage(word);
  if (wikipediaUrl && isDisplayableHttpImageUrl(wikipediaUrl, word)) {
    return wikipediaUrl;
  }

  return getDefaultLearningImageDataUrl(word, pos);
}
