/**
 * Generate curated stock-photo keyword files for all preset rank bands (~32k words).
 * Run: npm run generate:keywords
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getWordsByRangeId } from "../src/data/preset-vocabulary";
import { curateImageSearchPhrase } from "../src/lib/curate-image-keyword";

type BandSpec = {
  rangeIds: string[];
  exportName: string;
  label: string;
  fileName: string;
  format: "ts" | "json";
};

const BANDS: BandSpec[] = [
  {
    rangeIds: ["101-200", "201-300"],
    exportName: "CURATED_IMAGE_KEYWORDS_RANK_101_300",
    label: "101–300",
    fileName: "curated-image-keywords-rank-101-300.ts",
    format: "ts",
  },
  {
    rangeIds: ["301-500"],
    exportName: "CURATED_IMAGE_KEYWORDS_RANK_301_500",
    label: "301–500",
    fileName: "curated-image-keywords-rank-301-500.ts",
    format: "ts",
  },
  {
    rangeIds: ["501-1000"],
    exportName: "CURATED_IMAGE_KEYWORDS_RANK_501_1000",
    label: "501–1k",
    fileName: "curated-image-keywords-rank-501-1000.ts",
    format: "ts",
  },
  {
    rangeIds: ["1001-3000"],
    exportName: "CURATED_IMAGE_KEYWORDS_RANK_1001_3000",
    label: "1k–3k",
    fileName: "curated-image-keywords-rank-1001-3000.ts",
    format: "ts",
  },
  {
    rangeIds: ["3001-5000"],
    exportName: "CURATED_IMAGE_KEYWORDS_RANK_3001_5000",
    label: "3k–5k",
    fileName: "curated-image-keywords-rank-3001-5000.ts",
    format: "ts",
  },
  {
    rangeIds: ["5001-plus"],
    exportName: "CURATED_IMAGE_KEYWORDS_RANK_5001_PLUS",
    label: "5001+",
    fileName: "curated-image-keywords-rank-5001-plus.json",
    format: "json",
  },
];

function generateBand(spec: BandSpec) {
  const entries: Record<string, string> = {};

  for (const rangeId of spec.rangeIds) {
    const words = getWordsByRangeId(rangeId);
    for (const { word } of words) {
      entries[word] = curateImageSearchPhrase(word);
    }
  }

  const sorted = Object.entries(entries).sort(([a], [b]) => a.localeCompare(b));
  const path = resolve(process.cwd(), "src/data", spec.fileName);

  if (spec.format === "json") {
    const json = Object.fromEntries(sorted);
    writeFileSync(path, `${JSON.stringify(json)}\n`, "utf8");
    console.log(`Wrote ${path} (${sorted.length} entries, JSON)`);
    return;
  }

  const lines = sorted
    .map(([word, phrase]) => `  ${word}: "${phrase.replace(/"/g, '\\"')}",`)
    .join("\n");

  const content = `/**
 * Stock-photo search phrases for preset rank ${spec.label}.
 * Auto-generated by scripts/generate-curated-keywords.ts — concrete scenes, not the word alone.
 */
export const ${spec.exportName}: Readonly<Record<string, string>> = {
${lines}
};
`;

  writeFileSync(path, content, "utf8");
  console.log(`Wrote ${path} (${sorted.length} entries)`);
}

for (const band of BANDS) {
  generateBand(band);
}

console.log("Done — curated keywords generated for all rank bands.");
