/**
 * Unified lookup for pre-generated curated stock-photo keywords (~32k words).
 * Server-side only — safe to import large band files + JSON.
 */

import { CURATED_IMAGE_KEYWORDS_RANK_1_100 } from "@/data/curated-image-keywords-rank-1-100";
import { CURATED_IMAGE_KEYWORDS_RANK_101_300 } from "@/data/curated-image-keywords-rank-101-300";
import { CURATED_IMAGE_KEYWORDS_RANK_301_500 } from "@/data/curated-image-keywords-rank-301-500";
import { CURATED_IMAGE_KEYWORDS_RANK_501_1000 } from "@/data/curated-image-keywords-rank-501-1000";
import { CURATED_IMAGE_KEYWORDS_RANK_1001_3000 } from "@/data/curated-image-keywords-rank-1001-3000";
import { CURATED_IMAGE_KEYWORDS_RANK_3001_5000 } from "@/data/curated-image-keywords-rank-3001-5000";
import curatedRank5001Plus from "@/data/curated-image-keywords-rank-5001-plus.json";
import { isWeakAutoGeneratedPhrase } from "@/lib/image-keyword-utils";

const CURATED_BY_WORD: Readonly<Record<string, string>> = {
  ...CURATED_IMAGE_KEYWORDS_RANK_1_100,
  ...CURATED_IMAGE_KEYWORDS_RANK_101_300,
  ...CURATED_IMAGE_KEYWORDS_RANK_301_500,
  ...CURATED_IMAGE_KEYWORDS_RANK_501_1000,
  ...CURATED_IMAGE_KEYWORDS_RANK_1001_3000,
  ...CURATED_IMAGE_KEYWORDS_RANK_3001_5000,
  ...curatedRank5001Plus,
};

export function lookupCuratedImageKeyword(word: string): string | undefined {
  const key = word.trim().toLowerCase();
  const phrase = CURATED_BY_WORD[key];
  if (!phrase) return undefined;
  if (isWeakAutoGeneratedPhrase(phrase, key)) return undefined;
  return phrase;
}

export function countCuratedImageKeywords(): number {
  return Object.keys(CURATED_BY_WORD).length;
}

export { CURATED_BY_WORD };
